use serde_json::Value;
use std::collections::BTreeSet;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_schema.rs");

    let full_schema_path = Path::new("tools/compiled_protocol_schema.json");
    if !full_schema_path.exists() {
        panic!(
            "tools/compiled_protocol_schema.json not found. Run `cargo run --bin sts_dev_tool -- sync-schema` first."
        );
    }

    println!("cargo:rerun-if-changed=tools/compiled_protocol_schema.json");

    let schema_content = fs::read_to_string(full_schema_path).unwrap();
    let parsed: Value = serde_json::from_str(&schema_content).unwrap();

    let mut generated_code = String::new();
    generated_code.push_str(
        "// ============================================================================\n",
    );
    generated_code.push_str("// AUTO-GENERATED by build.rs from compiled_protocol_schema.json\n");
    generated_code.push_str("// DO NOT EDIT MANUALLY\n");
    generated_code.push_str(
        "// ============================================================================\n\n",
    );

    if let Some(enums) = parsed["enums"].as_object() {
        for (enum_key, enum_def) in enums {
            if enum_key == "card_id" {
                continue;
            }
            if let (Some(rust_type), Some(fn_name), Some(entries)) = (
                enum_def["rust_type"].as_str(),
                enum_def["fn_name"].as_str(),
                enum_def["entries"].as_object(),
            ) {
                generated_code.push_str(&format!(
                    "pub(crate) fn {}_raw(s: &str) -> Option<{}> {{\n",
                    fn_name, rust_type
                ));
                generated_code.push_str("    match s {\n");

                for (rust_variant, entry_def) in entries {
                    if let Some(java_names) = entry_def["java"].as_array() {
                        let mut patterns = BTreeSet::new();
                        for j in java_names {
                            if let Some(j_str) = j.as_str() {
                                let normalized = j_str
                                    .chars()
                                    .filter(|c| c.is_ascii_alphanumeric())
                                    .map(|c| c.to_ascii_lowercase())
                                    .collect::<String>();
                                if !normalized.is_empty() {
                                    patterns.insert(format!("\"{}\"", normalized));
                                }
                            }
                        }

                        if !patterns.is_empty() {
                            let pattern_str = patterns.into_iter().collect::<Vec<_>>().join(" | ");
                            let status = entry_def
                                .get("status")
                                .and_then(|v| v.as_str())
                                .unwrap_or("mapped");
                            let emitted_rust_variant = entry_def
                                .get("rust")
                                .and_then(|v| v.as_str())
                                .unwrap_or(rust_variant);

                            if rust_variant == "None"
                                || entry_def.get("rust").is_some_and(|v| v.is_null())
                                || matches!(status, "unsupported" | "internal_only" | "unresolved")
                            {
                                generated_code
                                    .push_str(&format!("        {} => None,\n", pattern_str));
                            } else {
                                generated_code.push_str(&format!(
                                    "        {} => Some({}::{}),\n",
                                    pattern_str, rust_type, emitted_rust_variant
                                ));
                            }
                        }
                    }
                }

                generated_code.push_str("        _other => {\n");
                // generated_code.push_str("            eprintln!(\"  UNMAPPED {}: {:?}\", other);\n");
                generated_code.push_str("            None\n");
                generated_code.push_str("        }\n");
                generated_code.push_str("    }\n");
                generated_code.push_str("}\n\n");
            }
        }
    }

    fs::write(&dest_path, generated_code).unwrap();
}
