use serde_json::Value;
use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_schema.rs");

    // The schema file we're parsing. Ensure cargo triggers rebuild if it changes.
    let schema_path = "../../tools/protocol_schema.json";
    
    // We expect the build.rs to be in `sts_simulator/`
    let full_schema_path = Path::new("tools/protocol_schema.json");
    if !full_schema_path.exists() {
        // Just in case we're building from nested dir or different workspace
        println!("cargo:warning=tools/protocol_schema.json not found, skipping schema generation.");
        return;
    }

    println!("cargo:rerun-if-changed=tools/protocol_schema.json");

    let schema_content = fs::read_to_string(full_schema_path).unwrap();
    let parsed: Value = serde_json::from_str(&schema_content).unwrap();
    
    let mut generated_code = String::new();
    generated_code.push_str("// ============================================================================\n");
    generated_code.push_str("// AUTO-GENERATED by build.rs from protocol_schema.json\n");
    generated_code.push_str("// DO NOT EDIT MANUALLY\n");
    generated_code.push_str("// ============================================================================\n\n");

    if let Some(enums) = parsed["enums"].as_object() {
        for (enum_key, enum_def) in enums {
            if let (Some(rust_type), Some(fn_name), Some(entries)) = (
                enum_def["rust_type"].as_str(),
                enum_def["fn_name"].as_str(),
                enum_def["entries"].as_object(),
            ) {
                generated_code.push_str(&format!("pub fn {}(s: &str) -> Option<{}> {{\n", fn_name, rust_type));
                generated_code.push_str("    match s {\n");

                for (rust_variant, entry_def) in entries {
                    if let Some(java_names) = entry_def["java"].as_array() {
                        let mut patterns = Vec::new();
                        for j in java_names {
                            if let Some(j_str) = j.as_str() {
                                patterns.push(format!("\"{}\"", j_str));
                            }
                        }
                        
                        if !patterns.is_empty() {
                            let pattern_str = patterns.join(" | ");
                            
                            if rust_variant == "None" 
                                || entry_def["scope"].as_str() == Some("non_combat") 
                                || entry_def["scope"].as_str() == Some("ui")
                                || entry_def["rust"].is_null()
                            {
                                generated_code.push_str(&format!("        {} => None,\n", pattern_str));
                            } else {
                                generated_code.push_str(&format!("        {} => Some({}::{}),\n", pattern_str, rust_type, rust_variant));
                            }
                        }
                    }
                }

                generated_code.push_str("        other => {\n");
                // generated_code.push_str("            eprintln!(\"  UNMAPPED {}: {:?}\", other);\n");
                generated_code.push_str("            None\n");
                generated_code.push_str("        }\n");
                generated_code.push_str("    }\n");
                generated_code.push_str("}\n\n");
            }
        }
    }

    fs::write(&dest_path, generated_code).unwrap();
}
