[package]
name = "sts_combat_knowledge"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false
autotests = false

[dependencies]
sts_core = { package = "sts_simulator", path = "../.." }
sts_combat_legacy = { path = "../sts_combat_legacy" }
sts_combat_planner = { path = "../sts_combat_planner" }

