pub mod colorless;
pub mod curses;
pub mod defect;
pub mod hooks;
pub mod ironclad;
pub mod silent;
pub mod status;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
#[repr(i32)]
pub enum CardId {
    Strike,
    Defend,
    Bash,
    Cleave,
    IronWave,
    PerfectedStrike,
    TwinStrike,
    ThunderClap,
    ShrugItOff,
    Flex,
    TrueGrit,
    Inflame,
    DemonForm,
    Corruption,
    HeavyBlade,
    Whirlwind,
    Bloodletting,
    Offering,
    SwordBoomerang,
    Dropkick,
    PommelStrike,
    Headbutt,
    Bludgeon,
    DoubleTap,
    FeelNoPain,
    DarkEmbrace,
    Sentinel,
    FiendFire,
    SeverSoul,
    SecondWind,
    Exhume,
    BurningPact,
    Reaper,
    Feed,
    BloodForBlood,
    Rupture,
    Hemokinesis,
    Combust,
    Brutality,
    LimitBreak,
    SpotWeakness,
    Barricade,
    Entrench,
    Juggernaut,
    FlameBarrier,
    Metallicize,
    GhostlyArmor,
    Impervious,
    PowerThrough,
    Evolve,
    FireBreathing,
    Immolate,
    WildStrike,
    RecklessCharge,
    Havoc,
    Warcry,
    BattleTrance,
    Rampage,
    SearingBlow,
    Anger,
    Armaments,
    DualWield,
    InfernalBlade,
    SeeingRed,
    Rage,
    Berserk,
    Shockwave,
    Uppercut,
    Clothesline,
    Disarm,
    Intimidate,
    Carnage,
    Clash,
    BodySlam,
    Pummel,
    // Status
    Burn,
    Dazed,
    Slimed,
    Wound,
    Void,
    Parasite,
    Regret,
    AscendersBane,
    Clumsy,
    CurseOfTheBell,
    Decay,
    Doubt,
    Injury,
    Necronomicurse,
    Normality,
    Pain,
    Pride,
    Shame,
    Writhe,
    Miracle,
    Shiv,
    Bite,
    Apparition,
    Madness,
    RitualDagger,
    JAX,
    Finesse,
    // Colorless — Uncommon
    BandageUp,
    Blind,
    DarkShackles,
    DeepBreath,
    Discovery,
    DramaticEntrance,
    Enlightenment,
    FlashOfSteel,
    Forethought,
    GoodInstincts,
    Impatience,
    JackOfAllTrades,
    MindBlast,
    Panacea,
    PanicButton,
    Purity,
    SwiftStrike,
    Trip,
    // Colorless — Rare
    Apotheosis,
    Chrysalis,
    HandOfGreed,
    Magnetism,
    MasterOfStrategy,
    Mayhem,
    Metamorphosis,
    Panache,
    SadisticNature,
    SecretTechnique,
    SecretWeapon,
    TheBomb,
    ThinkingAhead,
    Transmutation,
    Violence,
    StrikeG,
    DefendG,
    Neutralize,
    Survivor,
    DeadlyPoison,
    BouncingFlask,
    Catalyst,
    NoxiousFumes,
    Footwork,
    BladeDance,
    Blur,
    CloakAndDagger,
    Backflip,
    Acrobatics,
    Prepared,
    DaggerThrow,
    PoisonedStab,
    DaggerSpray,
    Adrenaline,
    AfterImage,
    Burst,
    Reflex,
    Tactician,
    Deflect,
    QuickSlash,
    Slice,
    FlyingKnee,
    DodgeAndRoll,
    Doppelganger,
    SuckerPunch,
    Outmaneuver,
    SneakyStrike,
    Dash,
    Bane,
    AllOutAttack,
    Choke,
    Concentrate,
    CorpseExplosion,
    CripplingPoison,
    CalculatedGamble,
    EndlessAgony,
    Envenom,
    StormOfSteel,
    Unload,
    PiercingWail,
    Backstab,
    RiddleWithHoles,
    Setup,
    Skewer,
    DieDieDie,
    Finisher,
    Flechettes,
    HeelHook,
    Expertise,
    EscapePlan,
    Predator,
    Accuracy,
    Caltrops,
    InfiniteBlades,
    LegSweep,
    Malaise,
    PhantasmalKiller,
    Eviscerate,
    GlassKnife,
    GrandFinale,
    WraithForm,
    MasterfulStab,
    Terror,
    Nightmare,
    AThousandCuts,
    BulletTime,
    ToolsOfTheTrade,
    WellLaidPlans,
    Alchemize,
    Distraction,
    StrikeB,
    DefendB,
    Zap,
    Dualcast,
    BallLightning,
    BeamCell,
    ColdSnap,
    ConserveBattery,
    Coolheaded,
    Leap,
    Turbo,
    SweepingBeam,
    Hologram,
    Stack,
    CompileDriver,
    Barrage,
    GoForTheEyes,
    Recursion,
    Streamline,
    Rebound,
    Claw,
    SteamBarrier,
    Defragment,
    Fusion,
    Glacier,
    Skim,
    Overclock,
    DoubleEnergy,
    Reprogram,
    Melter,
    Ftl,
    RipAndTear,
    Tempest,
    Darkness,
    Aggregate,
    AutoShields,
    BootSequence,
    Capacitor,
    Chill,
    ReinforcedBody,
    DoomAndGloom,
    Consume,
    Sunder,
    Chaos,
    Buffer,
    Equilibrium,
    SelfRepair,
    LockOn,
    CoreSurge,
    BiasedCognition,
    Loop,
    MeteorStrike,
    Hyperbeam,
    Electrodynamics,
    Rainbow,
    Impulse,
    MachineLearning,
    StaticDischarge,
    // Add more as we expand
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum CardType {
    Attack,
    Skill,
    Power,
    Status,
    Curse,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum CardRarity {
    Basic,
    Common,
    Uncommon,
    Rare,
    Special,
    Curse,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum CardTarget {
    Enemy,
    AllEnemy,
    SelfAndEnemy,
    SelfTarget,
    None,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub enum CardTag {
    Strike,
    StarterStrike,
    StarterDefend,
    Healing,
    Empty,
}

pub struct CardDefinition {
    pub id: CardId,
    pub name: &'static str,
    pub card_type: CardType,
    pub rarity: CardRarity,
    pub cost: i8, // -1 for X cost, -2 for unplayable
    pub base_damage: i32,
    pub base_block: i32,
    pub base_magic: i32,
    pub target: CardTarget,
    pub is_multi_damage: bool,
    pub exhaust: bool,
    pub ethereal: bool,
    pub innate: bool,
    pub tags: &'static [CardTag],
    pub upgrade_damage: i32,
    pub upgrade_block: i32,
    pub upgrade_magic: i32,
}

fn build_curse(id: CardId, name: &'static str, cost: i8) -> CardDefinition {
    let mut def = CardDefinition {
        id,
        name,
        card_type: CardType::Curse,
        rarity: CardRarity::Curse,
        cost,
        base_damage: 0,
        base_block: 0,
        base_magic: 0,
        target: CardTarget::None,
        is_multi_damage: false,
        exhaust: false,
        ethereal: false,
        innate: false,
        tags: &[],
        upgrade_damage: 0,
        upgrade_block: 0,
        upgrade_magic: 0,
    };

    if id == CardId::AscendersBane
        || id == CardId::CurseOfTheBell
        || id == CardId::Necronomicurse
        || id == CardId::Pride
    {
        def.rarity = CardRarity::Special;
    }

    if id == CardId::AscendersBane || id == CardId::Clumsy {
        def.ethereal = true;
    }

    if id == CardId::Writhe || id == CardId::Pride {
        def.innate = true;
    }

    if id == CardId::Pride {
        def.exhaust = true;
    }

    def
}

/// Dispatches card-specific logic that natively occurs exactly when a card is exhausted.
/// Base Slay the Spire has only two cards that override `triggerOnExhaust()`:
/// 1. Sentinel (Gain Energy)
/// 2. Necronomicurse (Clone itself back to hand)
pub fn resolve_card_on_exhaust(
    card: &crate::runtime::combat::CombatCard,
    _state: &crate::runtime::combat::CombatState,
) -> Vec<crate::runtime::action::ActionInfo> {
    match card.id {
        CardId::Necronomicurse => vec![crate::runtime::action::ActionInfo {
            action: crate::runtime::action::Action::MakeTempCardInHand {
                card_id: CardId::Necronomicurse,
                amount: 1,
                upgraded: false,
            },
            insertion_mode: crate::runtime::action::AddTo::Bottom,
        }],
        CardId::Sentinel => vec![crate::runtime::action::ActionInfo {
            action: crate::runtime::action::Action::GainEnergy {
                amount: if card.upgrades > 0 { 3 } else { 2 },
            },
            insertion_mode: crate::runtime::action::AddTo::Top,
        }],
        _ => vec![],
    }
}

pub fn is_starter_strike(id: CardId) -> bool {
    matches!(id, CardId::Strike | CardId::StrikeG | CardId::StrikeB)
}

pub fn is_starter_defend(id: CardId) -> bool {
    matches!(id, CardId::Defend | CardId::DefendG | CardId::DefendB)
}

pub fn is_starter_basic(id: CardId) -> bool {
    is_starter_strike(id) || is_starter_defend(id)
}

pub fn is_innate_card(card: &crate::runtime::combat::CombatCard) -> bool {
    get_card_definition(card.id).innate
        || matches!(card.id, CardId::Brutality) && card.upgrades > 0
        || matches!(card.id, CardId::AfterImage) && card.upgrades > 0
        || matches!(card.id, CardId::InfiniteBlades) && card.upgrades > 0
        || matches!(card.id, CardId::Chill) && card.upgrades > 0
        || matches!(card.id, CardId::MachineLearning) && card.upgrades > 0
}

pub fn get_card_definition(id: CardId) -> CardDefinition {
    match id {
        CardId::AscendersBane => build_curse(CardId::AscendersBane, "Ascender's Bane", -2),
        CardId::Clumsy => build_curse(CardId::Clumsy, "Clumsy", -2),
        CardId::CurseOfTheBell => build_curse(CardId::CurseOfTheBell, "Curse of the Bell", -2),
        CardId::Decay => build_curse(CardId::Decay, "Decay", -2),
        CardId::Doubt => build_curse(CardId::Doubt, "Doubt", -2),
        CardId::Injury => build_curse(CardId::Injury, "Injury", -2),
        CardId::Necronomicurse => build_curse(CardId::Necronomicurse, "Necronomicurse", -2),
        CardId::Normality => build_curse(CardId::Normality, "Normality", -2),
        CardId::Pain => build_curse(CardId::Pain, "Pain", -2),
        CardId::Pride => build_curse(CardId::Pride, "Pride", 1),
        CardId::Shame => build_curse(CardId::Shame, "Shame", -2),
        CardId::Writhe => build_curse(CardId::Writhe, "Writhe", -2),
        CardId::Apparition => colorless::apparition::definition(),
        CardId::Madness => colorless::madness::definition(),
        CardId::RitualDagger => colorless::ritual_dagger::definition(),
        CardId::JAX => colorless::jax::definition(),
        CardId::Finesse => colorless::finesse::definition(),
        // Colorless — Uncommon
        CardId::BandageUp => colorless::bandage_up::definition(),
        CardId::Blind => colorless::blind::definition(),
        CardId::DarkShackles => colorless::dark_shackles::definition(),
        CardId::DeepBreath => colorless::deep_breath::definition(),
        CardId::Discovery => colorless::discovery::definition(),
        CardId::DramaticEntrance => colorless::dramatic_entrance::definition(),
        CardId::Enlightenment => colorless::enlightenment::definition(),
        CardId::FlashOfSteel => colorless::flash_of_steel::definition(),
        CardId::Forethought => colorless::forethought::definition(),
        CardId::GoodInstincts => colorless::good_instincts::definition(),
        CardId::Impatience => colorless::impatience::definition(),
        CardId::JackOfAllTrades => colorless::jack_of_all_trades::definition(),
        CardId::MindBlast => colorless::mind_blast::definition(),
        CardId::Panacea => colorless::panacea::definition(),
        CardId::PanicButton => colorless::panic_button::definition(),
        CardId::Purity => colorless::purity::definition(),
        CardId::SwiftStrike => colorless::swift_strike::definition(),
        CardId::Trip => colorless::trip::definition(),
        // Colorless — Rare
        CardId::Apotheosis => colorless::apotheosis::definition(),
        CardId::Chrysalis => colorless::chrysalis::definition(),
        CardId::HandOfGreed => colorless::hand_of_greed::definition(),
        CardId::Magnetism => colorless::magnetism::definition(),
        CardId::MasterOfStrategy => colorless::master_of_strategy::definition(),
        CardId::Mayhem => colorless::mayhem::definition(),
        CardId::Metamorphosis => colorless::metamorphosis::definition(),
        CardId::Panache => colorless::panache::definition(),
        CardId::SadisticNature => colorless::sadistic_nature::definition(),
        CardId::SecretTechnique => colorless::secret_technique::definition(),
        CardId::SecretWeapon => colorless::secret_weapon::definition(),
        CardId::TheBomb => colorless::the_bomb::definition(),
        CardId::ThinkingAhead => colorless::thinking_ahead::definition(),
        CardId::Transmutation => colorless::transmutation::definition(),
        CardId::Violence => colorless::violence::definition(),
        CardId::Parasite => CardDefinition {
            id: CardId::Parasite,
            name: "Parasite",
            card_type: CardType::Curse,
            rarity: CardRarity::Curse,
            cost: -2, // Unplayable
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: false,
            ethereal: false,
            innate: false,
            tags: &[],
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Regret => CardDefinition {
            id: CardId::Regret,
            name: "Regret",
            card_type: CardType::Curse,
            rarity: CardRarity::Curse,
            cost: -2, // Unplayable
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: false,
            ethereal: false,
            innate: false,
            tags: &[],
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Strike => ironclad::strike::definition(),
        CardId::Defend => ironclad::defend::definition(),
        CardId::StrikeG => silent::strike_green::definition(),
        CardId::DefendG => silent::defend_green::definition(),
        CardId::StrikeB => defect::strike_blue::definition(),
        CardId::DefendB => defect::defend_blue::definition(),
        CardId::Zap => defect::zap::definition(),
        CardId::Dualcast => defect::dualcast::definition(),
        CardId::BallLightning => defect::ball_lightning::definition(),
        CardId::BeamCell => defect::beam_cell::definition(),
        CardId::ColdSnap => defect::cold_snap::definition(),
        CardId::ConserveBattery => defect::conserve_battery::definition(),
        CardId::Coolheaded => defect::coolheaded::definition(),
        CardId::Leap => defect::leap::definition(),
        CardId::Turbo => defect::turbo::definition(),
        CardId::SweepingBeam => defect::sweeping_beam::definition(),
        CardId::Hologram => defect::hologram::definition(),
        CardId::Stack => defect::stack::definition(),
        CardId::CompileDriver => defect::compile_driver::definition(),
        CardId::Barrage => defect::barrage::definition(),
        CardId::GoForTheEyes => defect::go_for_the_eyes::definition(),
        CardId::Recursion => defect::recursion::definition(),
        CardId::Streamline => defect::streamline::definition(),
        CardId::Rebound => defect::rebound::definition(),
        CardId::Claw => defect::claw::definition(),
        CardId::SteamBarrier => defect::steam_barrier::definition(),
        CardId::Defragment => defect::defragment::definition(),
        CardId::Fusion => defect::fusion::definition(),
        CardId::Glacier => defect::glacier::definition(),
        CardId::Skim => defect::skim::definition(),
        CardId::Overclock => defect::overclock::definition(),
        CardId::DoubleEnergy => defect::double_energy::definition(),
        CardId::Reprogram => defect::reprogram::definition(),
        CardId::Melter => defect::melter::definition(),
        CardId::Ftl => defect::ftl::definition(),
        CardId::RipAndTear => defect::rip_and_tear::definition(),
        CardId::Tempest => defect::tempest::definition(),
        CardId::Darkness => defect::darkness::definition(),
        CardId::Aggregate => defect::aggregate::definition(),
        CardId::AutoShields => defect::auto_shields::definition(),
        CardId::BootSequence => defect::boot_sequence::definition(),
        CardId::Capacitor => defect::capacitor::definition(),
        CardId::Chill => defect::chill::definition(),
        CardId::ReinforcedBody => defect::reinforced_body::definition(),
        CardId::DoomAndGloom => defect::doom_and_gloom::definition(),
        CardId::Consume => defect::consume::definition(),
        CardId::Sunder => defect::sunder::definition(),
        CardId::Chaos => defect::chaos::definition(),
        CardId::Buffer => defect::buffer::definition(),
        CardId::Equilibrium => defect::equilibrium::definition(),
        CardId::SelfRepair => defect::self_repair::definition(),
        CardId::LockOn => defect::lock_on::definition(),
        CardId::CoreSurge => defect::core_surge::definition(),
        CardId::BiasedCognition => defect::biased_cognition::definition(),
        CardId::Loop => defect::loop_card::definition(),
        CardId::MeteorStrike => defect::meteor_strike::definition(),
        CardId::Hyperbeam => defect::hyperbeam::definition(),
        CardId::Electrodynamics => defect::electrodynamics::definition(),
        CardId::Rainbow => defect::rainbow::definition(),
        CardId::Impulse => defect::impulse::definition(),
        CardId::MachineLearning => defect::machine_learning::definition(),
        CardId::StaticDischarge => defect::static_discharge::definition(),
        CardId::Bash => ironclad::bash::definition(),
        CardId::Neutralize => silent::neutralize::definition(),
        CardId::Survivor => silent::survivor::definition(),
        CardId::Cleave => ironclad::cleave::definition(),
        CardId::IronWave => ironclad::iron_wave::definition(),
        CardId::PerfectedStrike => ironclad::perfected_strike::definition(),
        CardId::TwinStrike => ironclad::twin_strike::definition(),
        CardId::ThunderClap => ironclad::thunderclap::definition(),
        CardId::ShrugItOff => ironclad::shrug_it_off::definition(),
        CardId::Flex => ironclad::flex::definition(),
        CardId::TrueGrit => ironclad::true_grit::definition(),
        CardId::Inflame => ironclad::inflame::definition(),
        CardId::DemonForm => ironclad::demon_form::definition(),
        CardId::Corruption => ironclad::corruption::definition(),
        CardId::HeavyBlade => ironclad::heavy_blade::definition(),
        CardId::Whirlwind => ironclad::whirlwind::definition(),
        CardId::Bloodletting => ironclad::bloodletting::definition(),
        CardId::Offering => ironclad::offering::definition(),
        CardId::SwordBoomerang => ironclad::sword_boomerang::definition(),
        CardId::Dropkick => ironclad::dropkick::definition(),
        CardId::PommelStrike => ironclad::pommel_strike::definition(),
        CardId::Headbutt => ironclad::headbutt::definition(),
        CardId::Bludgeon => ironclad::bludgeon::definition(),
        CardId::DoubleTap => ironclad::double_tap::definition(),
        CardId::FeelNoPain => ironclad::feel_no_pain::definition(),
        CardId::DarkEmbrace => ironclad::dark_embrace::definition(),
        CardId::Sentinel => ironclad::sentinel::definition(),
        CardId::FiendFire => ironclad::fiend_fire::definition(),
        CardId::SeverSoul => ironclad::sever_soul::definition(),
        CardId::SecondWind => ironclad::second_wind::definition(),
        CardId::Exhume => ironclad::exhume::definition(),
        CardId::BurningPact => ironclad::burning_pact::definition(),
        CardId::Reaper => ironclad::reaper::definition(),
        CardId::Feed => ironclad::feed::definition(),
        CardId::BloodForBlood => ironclad::blood_for_blood::definition(),
        CardId::Rupture => ironclad::rupture::definition(),
        CardId::Hemokinesis => ironclad::hemokinesis::definition(),
        CardId::Combust => ironclad::combust::definition(),
        CardId::Brutality => ironclad::brutality::definition(),
        CardId::LimitBreak => ironclad::limit_break::definition(),
        CardId::SpotWeakness => ironclad::spot_weakness::definition(),
        CardId::Barricade => ironclad::barricade::definition(),
        CardId::Entrench => ironclad::entrench::definition(),
        CardId::Juggernaut => ironclad::juggernaut::definition(),
        CardId::FlameBarrier => ironclad::flame_barrier::definition(),
        CardId::Metallicize => ironclad::metallicize::definition(),
        CardId::GhostlyArmor => ironclad::ghostly_armor::definition(),
        CardId::Impervious => ironclad::impervious::definition(),
        CardId::PowerThrough => ironclad::power_through::definition(),
        CardId::Evolve => ironclad::evolve::definition(),
        CardId::FireBreathing => ironclad::fire_breathing::definition(),
        CardId::Immolate => ironclad::immolate::definition(),
        CardId::WildStrike => ironclad::wild_strike::definition(),
        CardId::RecklessCharge => ironclad::reckless_charge::definition(),
        CardId::Havoc => ironclad::havoc::definition(),
        CardId::Warcry => ironclad::warcry::definition(),
        CardId::BattleTrance => ironclad::battle_trance::definition(),
        CardId::Rampage => ironclad::rampage::definition(),
        CardId::SearingBlow => ironclad::searing_blow::definition(),
        CardId::Anger => ironclad::anger::definition(),
        CardId::Armaments => ironclad::armaments::definition(),
        CardId::DualWield => ironclad::dual_wield::definition(),
        CardId::InfernalBlade => ironclad::infernal_blade::definition(),
        CardId::SeeingRed => ironclad::seeing_red::definition(),
        CardId::Rage => ironclad::rage::definition(),
        CardId::Berserk => ironclad::berserk::definition(),
        CardId::Shockwave => ironclad::shockwave::definition(),
        CardId::Uppercut => ironclad::uppercut::definition(),
        CardId::Clothesline => ironclad::clothesline::definition(),
        CardId::Disarm => ironclad::disarm::definition(),
        CardId::Intimidate => ironclad::intimidate::definition(),
        CardId::Carnage => ironclad::carnage::definition(),
        CardId::Clash => ironclad::clash::definition(),
        CardId::BodySlam => ironclad::body_slam::definition(),
        CardId::Pummel => ironclad::pummel::definition(),
        CardId::Wound => CardDefinition {
            id: CardId::Wound,
            name: "Wound",
            card_type: CardType::Status,
            rarity: CardRarity::Common,
            cost: -2,
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: false,
            ethereal: false,
            innate: false,
            tags: &[],
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Burn => CardDefinition {
            id: CardId::Burn,
            name: "Burn",
            card_type: CardType::Status,
            rarity: CardRarity::Common,
            cost: -2,
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: false,
            ethereal: false,
            innate: false,
            tags: &[], // In STS, Burn damages you at end of turn. We'll need a hook for this eventually,
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 2,
        },
        CardId::Dazed => CardDefinition {
            id: CardId::Dazed,
            name: "Dazed",
            card_type: CardType::Status,
            rarity: CardRarity::Common,
            cost: -2,
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: false,
            ethereal: true,
            innate: false,
            tags: &[], // Ethereal removes it,
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Slimed => CardDefinition {
            id: CardId::Slimed,
            name: "Slimed",
            card_type: CardType::Status,
            rarity: CardRarity::Common,
            cost: 1,
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: true,
            ethereal: false,
            innate: false,
            tags: &[],
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Void => CardDefinition {
            id: CardId::Void,
            name: "Void",
            card_type: CardType::Status,
            rarity: CardRarity::Common,
            cost: -2,
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: true,
            ethereal: true,
            innate: false,
            tags: &[],
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Miracle => CardDefinition {
            id: CardId::Miracle,
            name: "Miracle",
            card_type: CardType::Skill,
            rarity: CardRarity::Special,
            cost: 0,
            base_damage: 0,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::None,
            is_multi_damage: false,
            exhaust: true,
            ethereal: true,
            innate: false,
            tags: &[], // In game, Retain is actually hardcoded on Miracle,
            upgrade_damage: 0,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Shiv => CardDefinition {
            id: CardId::Shiv,
            name: "Shiv",
            card_type: CardType::Attack,
            rarity: CardRarity::Special,
            cost: 0,
            base_damage: 4,
            base_block: 0,
            base_magic: 0,
            target: CardTarget::Enemy,
            is_multi_damage: false,
            exhaust: true,
            ethereal: false,
            innate: false,
            tags: &[],
            upgrade_damage: 2,
            upgrade_block: 0,
            upgrade_magic: 0,
        },
        CardId::Bite => colorless::bite::definition(),
        CardId::DeadlyPoison => silent::deadly_poison::definition(),
        CardId::BouncingFlask => silent::bouncing_flask::definition(),
        CardId::Catalyst => silent::catalyst::definition(),
        CardId::NoxiousFumes => silent::noxious_fumes::definition(),
        CardId::Footwork => silent::footwork::definition(),
        CardId::BladeDance => silent::blade_dance::definition(),
        CardId::Blur => silent::blur::definition(),
        CardId::CloakAndDagger => silent::cloak_and_dagger::definition(),
        CardId::Backflip => silent::backflip::definition(),
        CardId::Acrobatics => silent::acrobatics::definition(),
        CardId::Prepared => silent::prepared::definition(),
        CardId::DaggerThrow => silent::dagger_throw::definition(),
        CardId::PoisonedStab => silent::poisoned_stab::definition(),
        CardId::DaggerSpray => silent::dagger_spray::definition(),
        CardId::Deflect => silent::deflect::definition(),
        CardId::QuickSlash => silent::quick_slash::definition(),
        CardId::Slice => silent::slice::definition(),
        CardId::FlyingKnee => silent::flying_knee::definition(),
        CardId::DodgeAndRoll => silent::dodge_and_roll::definition(),
        CardId::Doppelganger => silent::doppelganger::definition(),
        CardId::SuckerPunch => silent::sucker_punch::definition(),
        CardId::Outmaneuver => silent::outmaneuver::definition(),
        CardId::SneakyStrike => silent::sneaky_strike::definition(),
        CardId::Dash => silent::dash::definition(),
        CardId::Bane => silent::bane::definition(),
        CardId::AllOutAttack => silent::all_out_attack::definition(),
        CardId::Concentrate => silent::concentrate::definition(),
        CardId::Choke => silent::choke::definition(),
        CardId::CorpseExplosion => silent::corpse_explosion::definition(),
        CardId::CripplingPoison => silent::crippling_poison::definition(),
        CardId::CalculatedGamble => silent::calculated_gamble::definition(),
        CardId::EndlessAgony => silent::endless_agony::definition(),
        CardId::Envenom => silent::envenom::definition(),
        CardId::StormOfSteel => silent::storm_of_steel::definition(),
        CardId::Unload => silent::unload::definition(),
        CardId::PiercingWail => silent::piercing_wail::definition(),
        CardId::Backstab => silent::backstab::definition(),
        CardId::RiddleWithHoles => silent::riddle_with_holes::definition(),
        CardId::Setup => silent::setup::definition(),
        CardId::Skewer => silent::skewer::definition(),
        CardId::DieDieDie => silent::die_die_die::definition(),
        CardId::Finisher => silent::finisher::definition(),
        CardId::Flechettes => silent::flechettes::definition(),
        CardId::HeelHook => silent::heel_hook::definition(),
        CardId::Expertise => silent::expertise::definition(),
        CardId::EscapePlan => silent::escape_plan::definition(),
        CardId::Predator => silent::predator::definition(),
        CardId::Accuracy => silent::accuracy::definition(),
        CardId::Caltrops => silent::caltrops::definition(),
        CardId::InfiniteBlades => silent::infinite_blades::definition(),
        CardId::LegSweep => silent::leg_sweep::definition(),
        CardId::Malaise => silent::malaise::definition(),
        CardId::PhantasmalKiller => silent::phantasmal_killer::definition(),
        CardId::GlassKnife => silent::glass_knife::definition(),
        CardId::GrandFinale => silent::grand_finale::definition(),
        CardId::WraithForm => silent::wraith_form::definition(),
        CardId::Eviscerate => silent::eviscerate::definition(),
        CardId::MasterfulStab => silent::masterful_stab::definition(),
        CardId::Terror => silent::terror::definition(),
        CardId::AThousandCuts => silent::a_thousand_cuts::definition(),
        CardId::BulletTime => silent::bullet_time::definition(),
        CardId::ToolsOfTheTrade => silent::tools_of_the_trade::definition(),
        CardId::WellLaidPlans => silent::well_laid_plans::definition(),
        CardId::Nightmare => silent::nightmare::definition(),
        CardId::Alchemize => silent::alchemize::definition(),
        CardId::Distraction => silent::distraction::definition(),
        CardId::Adrenaline => silent::adrenaline::definition(),
        CardId::AfterImage => silent::after_image::definition(),
        CardId::Burst => silent::burst::definition(),
        CardId::Reflex => silent::reflex::definition(),
        CardId::Tactician => silent::tactician::definition(),
    }
}

include!("runtime_impl.rs");

/// Colorless pool — Uncommon tier (mirrors Java addColorlessCards: color=COLORLESS, rarity!=BASIC/SPECIAL)
pub const COLORLESS_UNCOMMON_POOL: &[CardId] = &[
    CardId::BandageUp,
    CardId::Blind,
    CardId::DarkShackles,
    CardId::DeepBreath,
    CardId::Discovery,
    CardId::DramaticEntrance,
    CardId::Enlightenment,
    CardId::Finesse,
    CardId::FlashOfSteel,
    CardId::Forethought,
    CardId::GoodInstincts,
    CardId::Impatience,
    CardId::JackOfAllTrades,
    CardId::Madness,
    CardId::MindBlast,
    CardId::Panacea,
    CardId::PanicButton,
    CardId::Purity,
    CardId::SwiftStrike,
    CardId::Trip,
];

/// Colorless pool — Rare tier
pub const COLORLESS_RARE_POOL: &[CardId] = &[
    CardId::Apotheosis,
    CardId::Chrysalis,
    CardId::HandOfGreed,
    CardId::Magnetism,
    CardId::MasterOfStrategy,
    CardId::Mayhem,
    CardId::Metamorphosis,
    CardId::Panache,
    CardId::SadisticNature,
    CardId::SecretTechnique,
    CardId::SecretWeapon,
    CardId::TheBomb,
    CardId::ThinkingAhead,
    CardId::Transmutation,
    CardId::Violence,
];

// ── Ironclad card pools (mirrors Java CardLibrary.addRedCards, excludes BASIC) ──

/// Ironclad Common pool (17 cards)
pub const IRONCLAD_COMMON_POOL: &[CardId] = &[
    CardId::Anger,
    CardId::Armaments,
    CardId::BodySlam,
    CardId::Clash,
    CardId::Cleave,
    CardId::Clothesline,
    CardId::Flex,
    CardId::Havoc,
    CardId::Headbutt,
    CardId::HeavyBlade,
    CardId::IronWave,
    CardId::PerfectedStrike,
    CardId::PommelStrike,
    CardId::ShrugItOff,
    CardId::SwordBoomerang,
    CardId::ThunderClap,
    CardId::TrueGrit,
    CardId::TwinStrike,
    CardId::Warcry,
    CardId::WildStrike,
];

/// Ironclad Uncommon pool (33 cards)
pub const IRONCLAD_UNCOMMON_POOL: &[CardId] = &[
    CardId::BattleTrance,
    CardId::BloodForBlood,
    CardId::Bloodletting,
    CardId::BurningPact,
    CardId::Carnage,
    CardId::Combust,
    CardId::DarkEmbrace,
    CardId::Disarm,
    CardId::Dropkick,
    CardId::DualWield,
    CardId::Entrench,
    CardId::Evolve,
    CardId::FeelNoPain,
    CardId::FireBreathing,
    CardId::FlameBarrier,
    CardId::GhostlyArmor,
    CardId::Hemokinesis,
    CardId::InfernalBlade,
    CardId::Inflame,
    CardId::Intimidate,
    CardId::Metallicize,
    CardId::PowerThrough,
    CardId::Pummel,
    CardId::Rage,
    CardId::Rampage,
    CardId::RecklessCharge,
    CardId::Rupture,
    CardId::SearingBlow,
    CardId::SecondWind,
    CardId::SeeingRed,
    CardId::Sentinel,
    CardId::SeverSoul,
    CardId::Shockwave,
    CardId::SpotWeakness,
    CardId::Uppercut,
    CardId::Whirlwind,
];

/// Ironclad Rare pool (16 cards)
pub const IRONCLAD_RARE_POOL: &[CardId] = &[
    CardId::Barricade,
    CardId::Berserk,
    CardId::Bludgeon,
    CardId::Brutality,
    CardId::Corruption,
    CardId::DemonForm,
    CardId::DoubleTap,
    CardId::Exhume,
    CardId::Feed,
    CardId::FiendFire,
    CardId::Immolate,
    CardId::Impervious,
    CardId::Juggernaut,
    CardId::LimitBreak,
    CardId::Offering,
    CardId::Reaper,
];

pub const SILENT_COMMON_POOL: &[CardId] = &[
    CardId::Acrobatics,
    CardId::Backflip,
    CardId::Bane,
    CardId::BladeDance,
    CardId::CloakAndDagger,
    CardId::DaggerSpray,
    CardId::DaggerThrow,
    CardId::DeadlyPoison,
    CardId::Deflect,
    CardId::DodgeAndRoll,
    CardId::FlyingKnee,
    CardId::Outmaneuver,
    CardId::PiercingWail,
    CardId::PoisonedStab,
    CardId::Prepared,
    CardId::QuickSlash,
    CardId::Slice,
    CardId::SuckerPunch,
    CardId::SneakyStrike,
];

pub const SILENT_UNCOMMON_POOL: &[CardId] = &[
    CardId::Accuracy,
    CardId::AllOutAttack,
    CardId::Backstab,
    CardId::Blur,
    CardId::BouncingFlask,
    CardId::CalculatedGamble,
    CardId::Caltrops,
    CardId::Catalyst,
    CardId::Choke,
    CardId::Concentrate,
    CardId::CripplingPoison,
    CardId::Dash,
    CardId::Distraction,
    CardId::EndlessAgony,
    CardId::EscapePlan,
    CardId::Eviscerate,
    CardId::Expertise,
    CardId::Finisher,
    CardId::Flechettes,
    CardId::Footwork,
    CardId::HeelHook,
    CardId::InfiniteBlades,
    CardId::LegSweep,
    CardId::MasterfulStab,
    CardId::NoxiousFumes,
    CardId::Predator,
    CardId::Reflex,
    CardId::RiddleWithHoles,
    CardId::Setup,
    CardId::Skewer,
    CardId::Tactician,
    CardId::Terror,
    CardId::WellLaidPlans,
];

pub const SILENT_RARE_POOL: &[CardId] = &[
    CardId::Adrenaline,
    CardId::AfterImage,
    CardId::Alchemize,
    CardId::AThousandCuts,
    CardId::BulletTime,
    CardId::Burst,
    CardId::CorpseExplosion,
    CardId::DieDieDie,
    CardId::Doppelganger,
    CardId::Envenom,
    CardId::GlassKnife,
    CardId::GrandFinale,
    CardId::Malaise,
    CardId::Nightmare,
    CardId::PhantasmalKiller,
    CardId::StormOfSteel,
    CardId::ToolsOfTheTrade,
    CardId::Unload,
    CardId::WraithForm,
];

/// Returns the pool for a given rarity (Ironclad).
/// Returns the pool of randomly obtainable curse cards.
/// Java: AbstractDungeon.returnRandomCurse() draws from this pool.
/// Excludes AscendersBane, Necronomicurse, CurseOfTheBell, and Pride.
pub fn get_curse_pool() -> &'static [CardId] {
    &[
        CardId::Clumsy,
        CardId::Decay,
        CardId::Doubt,
        CardId::Injury,
        CardId::Normality,
        CardId::Pain,
        CardId::Parasite,
        CardId::Regret,
        CardId::Shame,
        CardId::Writhe,
    ]
}

pub fn ironclad_pool_for_rarity(rarity: CardRarity) -> &'static [CardId] {
    match rarity {
        CardRarity::Common => IRONCLAD_COMMON_POOL,
        CardRarity::Uncommon => IRONCLAD_UNCOMMON_POOL,
        CardRarity::Rare => IRONCLAD_RARE_POOL,
        _ => IRONCLAD_COMMON_POOL,
    }
}

/// Returns all Ironclad cards of the given CardType from the pool matching the given rarity.
pub fn ironclad_pool_for_type(card_type: CardType) -> Vec<CardId> {
    let mut result = Vec::new();
    for &pool in &[
        IRONCLAD_COMMON_POOL,
        IRONCLAD_UNCOMMON_POOL,
        IRONCLAD_RARE_POOL,
    ] {
        for &id in pool {
            if get_card_definition(id).card_type == card_type {
                result.push(id);
            }
        }
    }
    result
}

pub fn silent_pool_for_rarity(rarity: CardRarity) -> &'static [CardId] {
    match rarity {
        CardRarity::Common => SILENT_COMMON_POOL,
        CardRarity::Uncommon => SILENT_UNCOMMON_POOL,
        CardRarity::Rare => SILENT_RARE_POOL,
        _ => SILENT_COMMON_POOL,
    }
}

pub fn silent_pool_for_type(card_type: CardType) -> Vec<CardId> {
    let mut result = Vec::new();
    for &pool in &[SILENT_COMMON_POOL, SILENT_UNCOMMON_POOL, SILENT_RARE_POOL] {
        for &id in pool {
            if get_card_definition(id).card_type == card_type {
                result.push(id);
            }
        }
    }
    result
}

/// Returns the pool for a given rarity (Defect). Stub until Defect cards are implemented.
pub fn defect_pool_for_rarity(_rarity: CardRarity) -> &'static [CardId] {
    &[]
}

/// Returns the pool for a given rarity (Watcher). Stub until Watcher cards are implemented.
pub fn watcher_pool_for_rarity(_rarity: CardRarity) -> &'static [CardId] {
    &[]
}

/// Returns the colorless pool for a given rarity.
pub fn colorless_pool_for_rarity(rarity: CardRarity) -> &'static [CardId] {
    match rarity {
        CardRarity::Uncommon => COLORLESS_UNCOMMON_POOL,
        CardRarity::Rare => COLORLESS_RARE_POOL,
        _ => &[],
    }
}

pub fn is_eligible_random_colorless_in_combat(id: CardId) -> bool {
    let def = get_card_definition(id);
    !def.tags.contains(&CardTag::Healing)
        && (COLORLESS_UNCOMMON_POOL.contains(&id) || COLORLESS_RARE_POOL.contains(&id))
}

pub fn random_colorless_in_combat_pool() -> Vec<CardId> {
    // Java: AbstractDungeon.returnTrulyRandomColorlessCardInCombat() iterates
    // srcColorlessCardPool.group, whose order comes from CardLibrary.addColorlessCards()
    // and AbstractDungeon.addColorlessCards(). This is not grouped by rarity; preserve the
    // original registration order so cardRandomRng picks line up with Java replay.
    [
        CardId::Apotheosis,
        CardId::Blind,
        CardId::Chrysalis,
        CardId::DarkShackles,
        CardId::DeepBreath,
        CardId::Discovery,
        CardId::DramaticEntrance,
        CardId::Enlightenment,
        CardId::Finesse,
        CardId::FlashOfSteel,
        CardId::Forethought,
        CardId::GoodInstincts,
        CardId::HandOfGreed,
        CardId::Impatience,
        CardId::JackOfAllTrades,
        CardId::Madness,
        CardId::Magnetism,
        CardId::MasterOfStrategy,
        CardId::Mayhem,
        CardId::Metamorphosis,
        CardId::MindBlast,
        CardId::Panacea,
        CardId::Panache,
        CardId::PanicButton,
        CardId::Purity,
        CardId::SadisticNature,
        CardId::SecretTechnique,
        CardId::SecretWeapon,
        CardId::SwiftStrike,
        CardId::TheBomb,
        CardId::ThinkingAhead,
        CardId::Transmutation,
        CardId::Trip,
        CardId::Violence,
    ]
    .iter()
    .copied()
    .filter(|&id| is_eligible_random_colorless_in_combat(id))
    .collect()
}

// ============================================================================
// Java Card ID Mapping
// ============================================================================
// These strings are the exact `card.cardID` values from the Java game source.
// They are used by the verification pipeline to map between Java and Rust.
// Source: decompiled from com.megacrit.cardcrawl.cards.*.java

/// Returns the Java `card.cardID` string for a given Rust CardId.
pub fn java_id(id: CardId) -> &'static str {
    match id {
        // --- Ironclad Basic ---
        CardId::Strike => "Strike_R",
        CardId::Defend => "Defend_R",
        CardId::Bash => "Bash",
        CardId::StrikeG => "Strike_G",
        CardId::DefendG => "Defend_G",
        CardId::StrikeB => "Strike_B",
        CardId::DefendB => "Defend_B",
        CardId::Zap => "Zap",
        CardId::Dualcast => "Dualcast",
        CardId::BallLightning => "Ball Lightning",
        CardId::BeamCell => "Beam Cell",
        CardId::ColdSnap => "Cold Snap",
        CardId::ConserveBattery => "Conserve Battery",
        CardId::Coolheaded => "Coolheaded",
        CardId::Leap => "Leap",
        CardId::Turbo => "Turbo",
        CardId::SweepingBeam => "Sweeping Beam",
        CardId::Hologram => "Hologram",
        CardId::Stack => "Stack",
        CardId::CompileDriver => "Compile Driver",
        CardId::Barrage => "Barrage",
        CardId::GoForTheEyes => "Go for the Eyes",
        CardId::Recursion => "Redo",
        CardId::Streamline => "Streamline",
        CardId::Rebound => "Rebound",
        CardId::Claw => "Gash",
        CardId::SteamBarrier => "Steam",
        CardId::Defragment => "Defragment",
        CardId::Fusion => "Fusion",
        CardId::Glacier => "Glacier",
        CardId::Skim => "Skim",
        CardId::Overclock => "Steam Power",
        CardId::DoubleEnergy => "Double Energy",
        CardId::Reprogram => "Reprogram",
        CardId::Melter => "Melter",
        CardId::Ftl => "FTL",
        CardId::RipAndTear => "Rip and Tear",
        CardId::Tempest => "Tempest",
        CardId::Darkness => "Darkness",
        CardId::Aggregate => "Aggregate",
        CardId::AutoShields => "Auto Shields",
        CardId::BootSequence => "BootSequence",
        CardId::Capacitor => "Capacitor",
        CardId::Chill => "Chill",
        CardId::ReinforcedBody => "Reinforced Body",
        CardId::DoomAndGloom => "Doom and Gloom",
        CardId::Consume => "Consume",
        CardId::Sunder => "Sunder",
        CardId::Chaos => "Chaos",
        CardId::Buffer => "Buffer",
        CardId::Equilibrium => "Undo",
        CardId::SelfRepair => "Self Repair",
        CardId::LockOn => "Lockon",
        CardId::CoreSurge => "Core Surge",
        CardId::BiasedCognition => "Biased Cognition",
        CardId::Loop => "Loop",
        CardId::MeteorStrike => "Meteor Strike",
        CardId::Hyperbeam => "Hyperbeam",
        CardId::Electrodynamics => "Electrodynamics",
        CardId::Rainbow => "Rainbow",
        CardId::Impulse => "Impulse",
        CardId::MachineLearning => "Machine Learning",
        CardId::StaticDischarge => "Static Discharge",
        CardId::Neutralize => "Neutralize",
        CardId::Survivor => "Survivor",

        // --- Ironclad Common ---
        CardId::Anger => "Anger",
        CardId::Armaments => "Armaments",
        CardId::BodySlam => "Body Slam",
        CardId::Clash => "Clash",
        CardId::Cleave => "Cleave",
        CardId::Clothesline => "Clothesline",
        CardId::Flex => "Flex",
        CardId::Havoc => "Havoc",
        CardId::Headbutt => "Headbutt",
        CardId::HeavyBlade => "Heavy Blade",
        CardId::IronWave => "Iron Wave",
        CardId::PerfectedStrike => "Perfected Strike",
        CardId::PommelStrike => "Pommel Strike",
        CardId::ShrugItOff => "Shrug It Off",
        CardId::SwordBoomerang => "Sword Boomerang",
        CardId::ThunderClap => "Thunderclap",
        CardId::TrueGrit => "True Grit",
        CardId::TwinStrike => "Twin Strike",
        CardId::Warcry => "Warcry",
        CardId::WildStrike => "Wild Strike",

        // --- Ironclad Uncommon ---
        CardId::BattleTrance => "Battle Trance",
        CardId::BloodForBlood => "Blood for Blood",
        CardId::Bloodletting => "Bloodletting",
        CardId::BurningPact => "Burning Pact",
        CardId::Carnage => "Carnage",
        CardId::Combust => "Combust",
        CardId::Corruption => "Corruption",
        CardId::DarkEmbrace => "Dark Embrace",
        CardId::Disarm => "Disarm",
        CardId::DoubleTap => "Double Tap",
        CardId::Dropkick => "Dropkick",
        CardId::DualWield => "Dual Wield",
        CardId::Entrench => "Entrench",
        CardId::Evolve => "Evolve",
        CardId::FeelNoPain => "Feel No Pain",
        CardId::FireBreathing => "Fire Breathing",
        CardId::FlameBarrier => "Flame Barrier",
        CardId::GhostlyArmor => "Ghostly Armor",
        CardId::Hemokinesis => "Hemokinesis",
        CardId::InfernalBlade => "Infernal Blade",
        CardId::Inflame => "Inflame",
        CardId::Intimidate => "Intimidate",
        CardId::Metallicize => "Metallicize",
        CardId::PowerThrough => "Power Through",
        CardId::Pummel => "Pummel",
        CardId::Rage => "Rage",
        CardId::Rampage => "Rampage",
        CardId::RecklessCharge => "Reckless Charge",
        CardId::Rupture => "Rupture",
        CardId::SearingBlow => "Searing Blow",
        CardId::SecondWind => "Second Wind",
        CardId::SeeingRed => "Seeing Red",
        CardId::Sentinel => "Sentinel",
        CardId::SeverSoul => "Sever Soul",
        CardId::Shockwave => "Shockwave",
        CardId::SpotWeakness => "Spot Weakness",
        CardId::Uppercut => "Uppercut",
        CardId::Whirlwind => "Whirlwind",

        // --- Ironclad Rare ---
        CardId::Barricade => "Barricade",
        CardId::Berserk => "Berserk",
        CardId::Bludgeon => "Bludgeon",
        CardId::Brutality => "Brutality",
        CardId::DemonForm => "Demon Form",
        CardId::Exhume => "Exhume",
        CardId::Feed => "Feed",
        CardId::FiendFire => "Fiend Fire",
        CardId::Immolate => "Immolate",
        CardId::Impervious => "Impervious",
        CardId::Juggernaut => "Juggernaut",
        CardId::LimitBreak => "Limit Break",
        CardId::Offering => "Offering",
        CardId::Reaper => "Reaper",

        // --- Status ---
        CardId::Burn => "Burn",
        CardId::Dazed => "Dazed",
        CardId::Slimed => "Slimed",
        CardId::Wound => "Wound",
        CardId::Void => "Void",

        // --- Curses ---
        CardId::AscendersBane => "AscendersBane",
        CardId::Clumsy => "Clumsy",
        CardId::CurseOfTheBell => "CurseOfTheBell",
        CardId::Decay => "Decay",
        CardId::Doubt => "Doubt",
        CardId::Injury => "Injury",
        CardId::Necronomicurse => "Necronomicurse",
        CardId::Normality => "Normality",
        CardId::Pain => "Pain",
        CardId::Parasite => "Parasite",
        CardId::Pride => "Pride",
        CardId::Regret => "Regret",
        CardId::Shame => "Shame",
        CardId::Writhe => "Writhe",

        // --- Special / Temp ---
        CardId::Miracle => "Miracle",
        CardId::Shiv => "Shiv",
        CardId::Bite => "Bite",
        CardId::Apparition => "Ghostly",
        CardId::Madness => "Madness",
        CardId::RitualDagger => "RitualDagger",
        CardId::JAX => "J.A.X.",
        CardId::Finesse => "Finesse",

        // --- Colorless Uncommon ---
        CardId::BandageUp => "Bandage Up",
        CardId::Blind => "Blind",
        CardId::DarkShackles => "Dark Shackles",
        CardId::DeepBreath => "Deep Breath",
        CardId::Discovery => "Discovery",
        CardId::DramaticEntrance => "Dramatic Entrance",
        CardId::Enlightenment => "Enlightenment",
        CardId::FlashOfSteel => "Flash of Steel",
        CardId::Forethought => "Forethought",
        CardId::GoodInstincts => "Good Instincts",
        CardId::Impatience => "Impatience",
        CardId::JackOfAllTrades => "Jack Of All Trades",
        CardId::MindBlast => "Mind Blast",
        CardId::Panacea => "Panacea",
        CardId::PanicButton => "PanicButton",
        CardId::Purity => "Purity",
        CardId::SwiftStrike => "Swift Strike",
        CardId::Trip => "Trip",

        // --- Colorless Rare ---
        CardId::Apotheosis => "Apotheosis",
        CardId::Chrysalis => "Chrysalis",
        CardId::HandOfGreed => "HandOfGreed",
        CardId::Magnetism => "Magnetism",
        CardId::MasterOfStrategy => "Master of Strategy",
        CardId::Mayhem => "Mayhem",
        CardId::Metamorphosis => "Metamorphosis",
        CardId::Panache => "Panache",
        CardId::SadisticNature => "Sadistic Nature",
        CardId::SecretTechnique => "Secret Technique",
        CardId::SecretWeapon => "Secret Weapon",
        CardId::TheBomb => "The Bomb",
        CardId::ThinkingAhead => "Thinking Ahead",
        CardId::Transmutation => "Transmutation",
        CardId::Violence => "Violence",
        CardId::DeadlyPoison => "Deadly Poison",
        CardId::BouncingFlask => "Bouncing Flask",
        CardId::Catalyst => "Catalyst",
        CardId::Blur => "Blur",
        CardId::Choke => "Choke",
        CardId::CorpseExplosion => "Corpse Explosion",
        CardId::CripplingPoison => "Crippling Poison",
        CardId::EndlessAgony => "Endless Agony",
        CardId::NoxiousFumes => "Noxious Fumes",
        CardId::Footwork => "Footwork",
        CardId::BladeDance => "Blade Dance",
        CardId::CloakAndDagger => "Cloak And Dagger",
        CardId::Backflip => "Backflip",
        CardId::Acrobatics => "Acrobatics",
        CardId::Prepared => "Prepared",
        CardId::DaggerThrow => "Dagger Throw",
        CardId::PoisonedStab => "Poisoned Stab",
        CardId::DaggerSpray => "Dagger Spray",
        CardId::Deflect => "Deflect",
        CardId::QuickSlash => "Quick Slash",
        CardId::Slice => "Slice",
        CardId::FlyingKnee => "Flying Knee",
        CardId::DodgeAndRoll => "Dodge and Roll",
        CardId::Doppelganger => "Doppelganger",
        CardId::SuckerPunch => "Sucker Punch",
        CardId::Outmaneuver => "Outmaneuver",
        CardId::SneakyStrike => "Underhanded Strike",
        CardId::Dash => "Dash",
        CardId::Bane => "Bane",
        CardId::AllOutAttack => "All Out Attack",
        CardId::Concentrate => "Concentrate",
        CardId::CalculatedGamble => "Calculated Gamble",
        CardId::StormOfSteel => "Storm of Steel",
        CardId::Envenom => "Envenom",
        CardId::Unload => "Unload",
        CardId::PiercingWail => "PiercingWail",
        CardId::Backstab => "Backstab",
        CardId::RiddleWithHoles => "Riddle With Holes",
        CardId::Setup => "Setup",
        CardId::Skewer => "Skewer",
        CardId::DieDieDie => "Die Die Die",
        CardId::Finisher => "Finisher",
        CardId::Flechettes => "Flechettes",
        CardId::HeelHook => "Heel Hook",
        CardId::Expertise => "Expertise",
        CardId::EscapePlan => "Escape Plan",
        CardId::Predator => "Predator",
        CardId::Accuracy => "Accuracy",
        CardId::Caltrops => "Caltrops",
        CardId::InfiniteBlades => "Infinite Blades",
        CardId::LegSweep => "Leg Sweep",
        CardId::Malaise => "Malaise",
        CardId::PhantasmalKiller => "Phantasmal Killer",
        CardId::Eviscerate => "Eviscerate",
        CardId::GlassKnife => "Glass Knife",
        CardId::GrandFinale => "Grand Finale",
        CardId::WraithForm => "Wraith Form v2",
        CardId::MasterfulStab => "Masterful Stab",
        CardId::Terror => "Terror",
        CardId::Nightmare => "Night Terror",
        CardId::AThousandCuts => "A Thousand Cuts",
        CardId::BulletTime => "Bullet Time",
        CardId::ToolsOfTheTrade => "Tools of the Trade",
        CardId::WellLaidPlans => "Well Laid Plans",
        CardId::Alchemize => "Venomology",
        CardId::Distraction => "Distraction",
        CardId::Adrenaline => "Adrenaline",
        CardId::AfterImage => "After Image",
        CardId::Burst => "Burst",
        CardId::Reflex => "Reflex",
        CardId::Tactician => "Tactician",
    }
}

/// Builds a reverse lookup: Java cardID string → Rust CardId.
/// Used by verification pipeline to map Java card data to Rust types.
pub fn build_java_id_map() -> std::collections::HashMap<&'static str, CardId> {
    use CardId::*;
    let all_ids = [
        Strike,
        Defend,
        Bash,
        StrikeG,
        DefendG,
        StrikeB,
        DefendB,
        Zap,
        Dualcast,
        BallLightning,
        BeamCell,
        ColdSnap,
        ConserveBattery,
        Coolheaded,
        Leap,
        Turbo,
        SweepingBeam,
        Hologram,
        Stack,
        CompileDriver,
        Barrage,
        GoForTheEyes,
        Recursion,
        Streamline,
        Rebound,
        Claw,
        SteamBarrier,
        Defragment,
        Fusion,
        Glacier,
        Skim,
        Overclock,
        DoubleEnergy,
        Reprogram,
        Melter,
        Ftl,
        RipAndTear,
        Tempest,
        Darkness,
        Aggregate,
        AutoShields,
        BootSequence,
        Capacitor,
        Chill,
        ReinforcedBody,
        DoomAndGloom,
        Consume,
        Sunder,
        Chaos,
        Buffer,
        Equilibrium,
        SelfRepair,
        LockOn,
        CoreSurge,
        BiasedCognition,
        Loop,
        MeteorStrike,
        Hyperbeam,
        Electrodynamics,
        Rainbow,
        Impulse,
        MachineLearning,
        StaticDischarge,
        Neutralize,
        Survivor,
        Anger,
        Armaments,
        BodySlam,
        Clash,
        Cleave,
        Clothesline,
        Flex,
        Havoc,
        Headbutt,
        HeavyBlade,
        IronWave,
        PerfectedStrike,
        PommelStrike,
        ShrugItOff,
        SwordBoomerang,
        ThunderClap,
        TrueGrit,
        TwinStrike,
        Warcry,
        WildStrike,
        BattleTrance,
        BloodForBlood,
        Bloodletting,
        BurningPact,
        Carnage,
        Combust,
        Corruption,
        DarkEmbrace,
        Disarm,
        DoubleTap,
        Dropkick,
        DualWield,
        Entrench,
        Evolve,
        FeelNoPain,
        FireBreathing,
        FlameBarrier,
        GhostlyArmor,
        Hemokinesis,
        InfernalBlade,
        Inflame,
        Intimidate,
        Metallicize,
        PowerThrough,
        Pummel,
        Rage,
        Rampage,
        RecklessCharge,
        Rupture,
        SearingBlow,
        SecondWind,
        SeeingRed,
        Sentinel,
        SeverSoul,
        Shockwave,
        SpotWeakness,
        Uppercut,
        Whirlwind,
        Barricade,
        Berserk,
        Bludgeon,
        Brutality,
        DemonForm,
        Exhume,
        Feed,
        FiendFire,
        Immolate,
        Impervious,
        Juggernaut,
        LimitBreak,
        Offering,
        Reaper,
        Burn,
        Dazed,
        Slimed,
        Wound,
        Void,
        AscendersBane,
        Clumsy,
        CurseOfTheBell,
        Decay,
        Doubt,
        Injury,
        Necronomicurse,
        Normality,
        Pain,
        Parasite,
        Pride,
        Regret,
        Shame,
        Writhe,
        Miracle,
        Shiv,
        Bite,
        Apparition,
        Madness,
        RitualDagger,
        JAX,
        Finesse,
        BandageUp,
        Blind,
        DarkShackles,
        DeepBreath,
        Discovery,
        DramaticEntrance,
        Enlightenment,
        FlashOfSteel,
        Forethought,
        GoodInstincts,
        Impatience,
        JackOfAllTrades,
        MindBlast,
        Panacea,
        PanicButton,
        Purity,
        SwiftStrike,
        Trip,
        Apotheosis,
        Chrysalis,
        HandOfGreed,
        Magnetism,
        MasterOfStrategy,
        Mayhem,
        Metamorphosis,
        Panache,
        SadisticNature,
        SecretTechnique,
        SecretWeapon,
        TheBomb,
        ThinkingAhead,
        Transmutation,
        Violence,
        DeadlyPoison,
        BouncingFlask,
        Catalyst,
        Blur,
        Choke,
        CorpseExplosion,
        CripplingPoison,
        EndlessAgony,
        NoxiousFumes,
        Footwork,
        BladeDance,
        CloakAndDagger,
        Backflip,
        Acrobatics,
        Prepared,
        DaggerThrow,
        PoisonedStab,
        DaggerSpray,
        Deflect,
        QuickSlash,
        Slice,
        FlyingKnee,
        DodgeAndRoll,
        Doppelganger,
        SuckerPunch,
        Outmaneuver,
        SneakyStrike,
        Dash,
        Bane,
        AllOutAttack,
        Concentrate,
        CalculatedGamble,
        Envenom,
        StormOfSteel,
        Unload,
        PiercingWail,
        Backstab,
        RiddleWithHoles,
        Setup,
        Skewer,
        DieDieDie,
        Finisher,
        Flechettes,
        HeelHook,
        Expertise,
        EscapePlan,
        Predator,
        Accuracy,
        Caltrops,
        InfiniteBlades,
        LegSweep,
        Malaise,
        PhantasmalKiller,
        Eviscerate,
        GlassKnife,
        GrandFinale,
        WraithForm,
        MasterfulStab,
        Terror,
        Nightmare,
        AThousandCuts,
        BulletTime,
        ToolsOfTheTrade,
        WellLaidPlans,
        Alchemize,
        Distraction,
        Adrenaline,
        AfterImage,
        Burst,
        Reflex,
        Tactician,
    ];
    let mut map = std::collections::HashMap::with_capacity(all_ids.len());
    for id in all_ids {
        map.insert(java_id(id), id);
    }
    map
}

#[cfg(test)]
mod tests;
