#![allow(unused_imports)]

use super::super::*;
use super::*;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub enum ActionPayload {
    AddCardToDeck(AddCardToDeckActionState),
    ApplyPoisonOnRandomMonster(ApplyPoisonOnRandomMonsterActionState),
    ApplyPower(ApplyPowerActionState),
    ApplyPowerToRandomEnemy(ApplyPowerToRandomEnemyActionState),
    AttackDamageRandomEnemy(AttackDamageRandomEnemyActionState),
    BetterDiscardPileToHand(BetterDiscardPileToHandActionState),
    BetterDrawPileToHand(BetterDrawPileToHandActionState),
    BurnIncrease(BurnIncreaseActionState),
    ChooseOneColorless(ChooseOneColorlessActionState),
    ConditionalDraw(ConditionalDrawActionState),
    Codex(CodexActionState),
    Damage(DamageActionState),
    DamageAllEnemies(DamageAllEnemiesActionState),
    DamageRandomEnemy(DamageRandomEnemyActionState),
    DiscardToHand(DiscardToHandActionState),
    DrawCard(DrawCardActionState),
    DrawPileToHand(DrawPileToHandActionState),
    Discard(DiscardActionState),
    DiscardSpecificCard(DiscardSpecificCardActionState),
    Discovery(DiscoveryActionState),
    EmptyDeckShuffle(EmptyDeckShuffleActionState),
    Exhaust(ExhaustActionState),
    ExhaustToHand(ExhaustToHandActionState),
    ExhaustSpecificCard(ExhaustSpecificCardActionState),
    ForeignInfluence(ForeignInfluenceActionState),
    GainEnergy(GainEnergyActionState),
    MakeTempCardInDiscard(MakeTempCardInDiscardActionState),
    MakeTempCardInDiscardAndDeck(MakeTempCardInDiscardAndDeckActionState),
    MakeTempCardInDrawPile(MakeTempCardInDrawPileActionState),
    MakeTempCardInHand(MakeTempCardInHandActionState),
    ModifyBlock(ModifyBlockActionState),
    NewQueueCard(NewQueueCardActionState),
    ObtainPotion(ObtainPotionActionState),
    PlayTopCard(PlayTopCardActionState),
    PutOnBottomOfDeck(PutOnBottomOfDeckActionState),
    PutOnDeck(PutOnDeckActionState),
    PummelDamage(PummelDamageActionState),
    QueueCard(QueueCardActionState),
    ReApplyPowers(ReApplyPowersActionState),
    ReduceCost(ReduceCostActionState),
    ReduceCostForTurn(ReduceCostForTurnActionState),
    ReducePower(ReducePowerActionState),
    RemoveSpecificPower(RemoveSpecificPowerActionState),
    ResetFlags(ResetFlagsActionState),
    ReviveMonster(ReviveMonsterActionState),
    RollMove(RollMoveActionState),
    Scry(ScryActionState),
    SetMove(SetMoveActionState),
    SetDontTrigger(SetDontTriggerActionState),
    ShowCard(ShowCardActionState),
    ShowCardAndPoof(ShowCardAndPoofActionState),
    SpawnMonster(SpawnMonsterActionState),
    Suicide(SuicideActionState),
    TransformCardInHand(TransformCardInHandActionState),
    Unlimbo(UnlimboActionState),
    UpdateCardDescription(UpdateCardDescriptionActionState),
    UseCard(UseCardActionState),
}

impl ActionPayload {
    pub fn java_source_class(&self) -> &'static str {
        match self {
            ActionPayload::AddCardToDeck(_) => "AddCardToDeckAction",
            ActionPayload::ApplyPoisonOnRandomMonster(_) => "ApplyPoisonOnRandomMonsterAction",
            ActionPayload::ApplyPower(_) => "ApplyPowerAction",
            ActionPayload::ApplyPowerToRandomEnemy(_) => "ApplyPowerToRandomEnemyAction",
            ActionPayload::AttackDamageRandomEnemy(_) => "AttackDamageRandomEnemyAction",
            ActionPayload::BetterDiscardPileToHand(_) => "BetterDiscardPileToHandAction",
            ActionPayload::BetterDrawPileToHand(_) => "BetterDrawPileToHandAction",
            ActionPayload::BurnIncrease(_) => "BurnIncreaseAction",
            ActionPayload::ChooseOneColorless(_) => "ChooseOneColorless",
            ActionPayload::ConditionalDraw(_) => "ConditionalDrawAction",
            ActionPayload::Codex(_) => "CodexAction",
            ActionPayload::Damage(_) => "DamageAction",
            ActionPayload::DamageAllEnemies(_) => "DamageAllEnemiesAction",
            ActionPayload::DamageRandomEnemy(_) => "DamageRandomEnemyAction",
            ActionPayload::DiscardToHand(_) => "DiscardToHandAction",
            ActionPayload::DrawCard(_) => "DrawCardAction",
            ActionPayload::DrawPileToHand(_) => "DrawPileToHandAction",
            ActionPayload::Discard(_) => "DiscardAction",
            ActionPayload::DiscardSpecificCard(_) => "DiscardSpecificCardAction",
            ActionPayload::Discovery(_) => "DiscoveryAction",
            ActionPayload::EmptyDeckShuffle(_) => "EmptyDeckShuffleAction",
            ActionPayload::Exhaust(_) => "ExhaustAction",
            ActionPayload::ExhaustSpecificCard(_) => "ExhaustSpecificCardAction",
            ActionPayload::ExhaustToHand(_) => "ExhaustToHandAction",
            ActionPayload::ForeignInfluence(_) => "ForeignInfluenceAction",
            ActionPayload::GainEnergy(_) => "GainEnergyAction",
            ActionPayload::MakeTempCardInDiscard(_) => "MakeTempCardInDiscardAction",
            ActionPayload::MakeTempCardInDiscardAndDeck(_) => "MakeTempCardInDiscardAndDeckAction",
            ActionPayload::MakeTempCardInDrawPile(_) => "MakeTempCardInDrawPileAction",
            ActionPayload::MakeTempCardInHand(_) => "MakeTempCardInHandAction",
            ActionPayload::ModifyBlock(_) => "ModifyBlockAction",
            ActionPayload::NewQueueCard(_) => "NewQueueCardAction",
            ActionPayload::ObtainPotion(_) => "ObtainPotionAction",
            ActionPayload::PlayTopCard(_) => "PlayTopCardAction",
            ActionPayload::PutOnBottomOfDeck(_) => "PutOnBottomOfDeckAction",
            ActionPayload::PutOnDeck(_) => "PutOnDeckAction",
            ActionPayload::PummelDamage(_) => "PummelDamageAction",
            ActionPayload::QueueCard(_) => "QueueCardAction",
            ActionPayload::ReApplyPowers(_) => "ReApplyPowersAction",
            ActionPayload::ReduceCost(_) => "ReduceCostAction",
            ActionPayload::ReduceCostForTurn(_) => "ReduceCostForTurnAction",
            ActionPayload::ReducePower(_) => "ReducePowerAction",
            ActionPayload::RemoveSpecificPower(_) => "RemoveSpecificPowerAction",
            ActionPayload::ResetFlags(_) => "ResetFlagsAction",
            ActionPayload::ReviveMonster(_) => "ReviveMonsterAction",
            ActionPayload::RollMove(_) => "RollMoveAction",
            ActionPayload::Scry(_) => "ScryAction",
            ActionPayload::SetMove(_) => "SetMoveAction",
            ActionPayload::SetDontTrigger(_) => "SetDontTriggerAction",
            ActionPayload::ShowCard(_) => "ShowCardAction",
            ActionPayload::ShowCardAndPoof(_) => "ShowCardAndPoofAction",
            ActionPayload::SpawnMonster(_) => "SpawnMonsterAction",
            ActionPayload::Suicide(_) => "SuicideAction",
            ActionPayload::TransformCardInHand(_) => "TransformCardInHandAction",
            ActionPayload::Unlimbo(_) => "UnlimboAction",
            ActionPayload::UpdateCardDescription(_) => "UpdateCardDescriptionAction",
            ActionPayload::UseCard(_) => "UseCardAction",
        }
    }
}
