//! JSON data loader with proper error handling.
//!
//! Loads card and monster definitions from JSON files generated by our Python ETL pipeline.

use std::collections::HashMap;
use std::fs;
use std::path::Path;

use thiserror::Error;

use crate::schema::CardDefinition;
use crate::enemy::MonsterDefinition;

/// Errors that can occur during loading.
#[derive(Error, Debug)]
pub enum LoaderError {
    #[error("Failed to read file '{path}': {source}")]
    FileRead {
        path: String,
        #[source]
        source: std::io::Error,
    },
    
    #[error("Failed to parse JSON from '{path}': {source}")]
    JsonParse {
        path: String,
        #[source]
        source: serde_json::Error,
    },
    
    #[error("Card '{0}' not found in library")]
    CardNotFound(String),
    
    #[error("Monster '{0}' not found in library")]
    MonsterNotFound(String),
    
    #[error("Empty card library loaded from '{0}'")]
    EmptyLibrary(String),
    
    #[error("Empty monster library loaded from '{0}'")]
    EmptyMonsterLibrary(String),
}

/// A library of card definitions loaded from JSON.
#[derive(Debug, Clone)]
pub struct CardLibrary {
    cards: HashMap<String, CardDefinition>,
}

impl CardLibrary {
    /// Load card definitions from a JSON file.
    ///
    /// # Arguments
    /// * `path` - Path to the cards.json file
    ///
    /// # Returns
    /// * `Ok(CardLibrary)` - Successfully loaded library
    /// * `Err(LoaderError)` - Error during loading
    ///
    /// # Example
    /// ```no_run
    /// use sts_sim::loader::CardLibrary;
    /// 
    /// let library = CardLibrary::load("data/cards.json")?;
    /// let bash = library.get("Bash")?;
    /// # Ok::<(), sts_sim::loader::LoaderError>(())
    /// ```
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self, LoaderError> {
        let path_ref = path.as_ref();
        
        // Auto-detect: if path is a directory, use load_dir
        if path_ref.is_dir() {
            return Self::load_dir(path);
        }
        
        let path_str = path_ref.display().to_string();
        
        // Read file contents
        let contents = fs::read_to_string(&path).map_err(|e| LoaderError::FileRead {
            path: path_str.clone(),
            source: e,
        })?;
        
        // Parse JSON array of card definitions
        let cards_vec: Vec<CardDefinition> = serde_json::from_str(&contents)
            .map_err(|e| LoaderError::JsonParse {
                path: path_str.clone(),
                source: e,
            })?;
        
        if cards_vec.is_empty() {
            return Err(LoaderError::EmptyLibrary(path_str));
        }
        
        // Build HashMap for O(1) lookup by ID
        let cards: HashMap<String, CardDefinition> = cards_vec
            .into_iter()
            .map(|card| (card.id.clone(), card))
            .collect();
        
        game_log!("[Loader] Loaded {} card definitions from '{}'", cards.len(), path_str);
        
        Ok(Self { cards })
    }
    
    /// Load card definitions from a directory of JSON files (recursive).
    ///
    /// Walks through all `.json` files in the directory tree and merges them
    /// into a single CardLibrary. This supports the split file layout:
    /// `data/cards/{color}/{rarity}.json`
    ///
    /// # Example
    /// ```no_run
    /// use sts_sim::loader::CardLibrary;
    /// 
    /// let library = CardLibrary::load_dir("data/cards")?;
    /// let bash = library.get("Bash")?;
    /// # Ok::<(), sts_sim::loader::LoaderError>(())
    /// ```
    pub fn load_dir<P: AsRef<Path>>(dir: P) -> Result<Self, LoaderError> {
        let dir_path = dir.as_ref();
        let dir_str = dir_path.display().to_string();
        
        if !dir_path.is_dir() {
            return Err(LoaderError::FileRead {
                path: dir_str,
                source: std::io::Error::new(
                    std::io::ErrorKind::NotFound,
                    "Path is not a directory",
                ),
            });
        }
        
        let mut all_cards = HashMap::new();
        let mut file_count = 0;
        
        // Recursively collect JSON files
        Self::walk_json_files(dir_path, &mut |file_path| {
            let file_str = file_path.display().to_string();
            let contents = fs::read_to_string(file_path).map_err(|e| LoaderError::FileRead {
                path: file_str.clone(),
                source: e,
            })?;
            
            let cards_vec: Vec<CardDefinition> = serde_json::from_str(&contents)
                .map_err(|e| LoaderError::JsonParse {
                    path: file_str.clone(),
                    source: e,
                })?;
            
            for card in cards_vec {
                all_cards.insert(card.id.clone(), card);
            }
            file_count += 1;
            Ok(())
        })?;
        
        if all_cards.is_empty() {
            return Err(LoaderError::EmptyLibrary(dir_str));
        }
        
        game_log!(
            "[Loader] Loaded {} card definitions from {} files in '{}'",
            all_cards.len(), file_count, dir_str
        );
        
        Ok(Self { cards: all_cards })
    }
    
    /// Recursively walk a directory and call `f` for each .json file.
    fn walk_json_files(
        dir: &Path,
        f: &mut dyn FnMut(&Path) -> Result<(), LoaderError>,
    ) -> Result<(), LoaderError> {
        let entries = fs::read_dir(dir).map_err(|e| LoaderError::FileRead {
            path: dir.display().to_string(),
            source: e,
        })?;
        
        let mut paths: Vec<_> = entries
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .collect();
        paths.sort(); // deterministic order
        
        for path in paths {
            if path.is_dir() {
                Self::walk_json_files(&path, f)?;
            } else if path.extension().and_then(|e| e.to_str()) == Some("json") {
                f(&path)?;
            }
        }
        
        Ok(())
    }
    
    /// Get a card definition by ID.
    pub fn get(&self, id: &str) -> Result<&CardDefinition, LoaderError> {
        self.cards
            .get(id)
            .ok_or_else(|| LoaderError::CardNotFound(id.to_string()))
    }
    
    /// Get a card definition by ID, returning None if not found.
    pub fn get_opt(&self, id: &str) -> Option<&CardDefinition> {
        self.cards.get(id)
    }
    
    /// Check if a card exists in the library.
    pub fn contains(&self, id: &str) -> bool {
        self.cards.contains_key(id)
    }
    
    /// Get the total number of cards in the library.
    pub fn len(&self) -> usize {
        self.cards.len()
    }
    
    /// Check if the library is empty.
    pub fn is_empty(&self) -> bool {
        self.cards.is_empty()
    }
    
    /// Iterate over all card definitions.
    pub fn iter(&self) -> impl Iterator<Item = &CardDefinition> {
        self.cards.values()
    }
    
    /// Get all card IDs.
    pub fn card_ids(&self) -> impl Iterator<Item = &String> {
        self.cards.keys()
    }
    
    /// Filter cards by type.
    pub fn cards_of_type(&self, card_type: crate::schema::CardType) -> Vec<&CardDefinition> {
        self.cards
            .values()
            .filter(|c| c.card_type == card_type)
            .collect()
    }
    
    /// Filter cards by color.
    pub fn cards_of_color(&self, color: crate::schema::CardColor) -> Vec<&CardDefinition> {
        self.cards
            .values()
            .filter(|c| c.color == Some(color))
            .collect()
    }
    
    /// Filter cards by rarity.
    pub fn cards_of_rarity(&self, rarity: crate::schema::CardRarity) -> Vec<&CardDefinition> {
        self.cards
            .values()
            .filter(|c| c.rarity == Some(rarity))
            .collect()
    }
    
    /// Get a random card from a named pool.
    ///
    /// Pool names match the HookEffect strings:
    /// - "Colorless" → cards with color=Colorless
    /// - "Common" → cards with rarity=Common (any color)
    /// - "Power" → cards with type=Power (any color/rarity)
    /// - "Attack" → cards with type=Attack
    /// - "Skill" → cards with type=Skill
    ///
    /// Returns None if pool is empty.
    pub fn get_random_card(&self, pool: &str, rng: &mut impl rand::Rng) -> Option<crate::schema::CardInstance> {
        use crate::schema::{CardType, CardColor, CardRarity, CardInstance};
        
        let candidates: Vec<&CardDefinition> = match pool {
            "Colorless" => self.cards.values()
                .filter(|c| c.color == Some(CardColor::Colorless))
                .collect(),
            "Common" => self.cards.values()
                .filter(|c| c.rarity == Some(CardRarity::Common))
                .filter(|c| c.card_type != CardType::Status && c.card_type != CardType::Curse)
                .collect(),
            "Power" => self.cards.values()
                .filter(|c| c.card_type == CardType::Power)
                .collect(),
            "Attack" => self.cards.values()
                .filter(|c| c.card_type == CardType::Attack)
                .collect(),
            "Skill" => self.cards.values()
                .filter(|c| c.card_type == CardType::Skill)
                .collect(),
            _ => self.cards.values()
                .filter(|c| c.card_type != CardType::Status && c.card_type != CardType::Curse)
                .collect(),
        };
        
        if candidates.is_empty() {
            return None;
        }
        
        let idx = rng.random_range(0..candidates.len());
        let def = candidates[idx];
        Some(CardInstance {
            definition_id: def.id.clone(),
            upgraded: false,
            base_cost: def.cost,
            current_cost: def.cost,
            is_ethereal: CardInstance::check_ethereal(&def.id),
            is_innate: CardInstance::check_innate(&def.id),
            self_retain: CardInstance::check_self_retain(&def.id),
            card_type: def.card_type,
        })
    }
    
    /// Get a random card filtered by player class color.
    ///
    /// This matches Java's approach where card pools are pre-filtered per character:
    /// - `Ironclad.getCardPool()` → `CardLibrary.addRedCards()` (only RED cards)
    /// - Status, Curse, Basic, and Special rarity cards are excluded
    /// - Pool name filters by type: "Attack", "Skill", "Power", or "any"
    ///
    /// Pass `None` for color to get any color card (PrismaticShard behavior).
    pub fn get_random_card_of_color(
        &self,
        pool: &str,
        color: Option<crate::schema::CardColor>,
        rng: &mut impl rand::Rng,
    ) -> Option<crate::schema::CardInstance> {
        use crate::schema::{CardType, CardColor, CardRarity, CardInstance};
        
        let candidates: Vec<&CardDefinition> = self.cards.values()
            .filter(|c| {
                // Exclude Status and Curse cards
                if c.card_type == CardType::Status || c.card_type == CardType::Curse {
                    return false;
                }
                // Exclude Basic (starter) and Special rarity — not in reward pools
                if c.rarity == Some(CardRarity::Basic) || c.rarity == Some(CardRarity::Special) {
                    return false;
                }
                
                // Filter by player class color if specified
                if let Some(class_color) = color {
                    if c.color != Some(class_color) {
                        return false;
                    }
                }
                
                // Filter by pool type
                match pool {
                    "Attack" => c.card_type == CardType::Attack,
                    "Skill" => c.card_type == CardType::Skill,
                    "Power" => c.card_type == CardType::Power,
                    "Colorless" => c.color == Some(CardColor::Colorless),
                    _ => true, // "any" or unrecognized = all types
                }
            })
            .collect();
        
        if candidates.is_empty() {
            return None;
        }
        
        let idx = rng.random_range(0..candidates.len());
        let def = candidates[idx];
        Some(CardInstance {
            definition_id: def.id.clone(),
            upgraded: false,
            base_cost: def.cost,
            current_cost: def.cost,
            is_ethereal: CardInstance::check_ethereal(&def.id),
            is_innate: CardInstance::check_innate(&def.id),
            self_retain: CardInstance::check_self_retain(&def.id),
            card_type: def.card_type,
        })
    }
}

/// Load the default card library from `data/cards/` directory.
pub fn load_default() -> Result<CardLibrary, LoaderError> {
    CardLibrary::load("data/cards")
}

/// A library of monster definitions loaded from v5 JSON.
#[derive(Debug, Clone)]
pub struct MonsterLibrary {
    /// Primary index: by monster id (e.g. "AcidSlime_L")
    by_id: HashMap<String, MonsterDefinition>,
    /// Secondary index: display name → id (e.g. "Acid Slime (L)" → "AcidSlime_L")
    by_name: HashMap<String, String>,
    /// Secondary index: java_id → id (e.g. "AcidSlime_L" → "AcidSlime_L")
    by_java_id: HashMap<String, String>,
}

impl MonsterLibrary {
    /// Load monster definitions from a v5 JSON file.
    ///
    /// The v5 format is a top-level dict: { "_meta": {...}, "MonsterName": {...}, ... }
    pub fn load<P: AsRef<Path>>(path: P) -> Result<Self, LoaderError> {
        let path_str = path.as_ref().display().to_string();
        
        let contents = fs::read_to_string(&path).map_err(|e| LoaderError::FileRead {
            path: path_str.clone(),
            source: e,
        })?;
        
        // Parse as generic JSON object
        let raw: serde_json::Value = serde_json::from_str(&contents)
            .map_err(|e| LoaderError::JsonParse {
                path: path_str.clone(),
                source: e,
            })?;
        
        let obj = raw.as_object().ok_or_else(|| LoaderError::JsonParse {
            path: path_str.clone(),
            source: serde_json::from_str::<serde_json::Value>("null").unwrap_err(),
        })?;
        
        let mut by_id = HashMap::new();
        let mut by_name = HashMap::new();
        let mut by_java_id = HashMap::new();
        
        for (key, value) in obj {
            // Skip _meta and similar keys
            if key.starts_with('_') {
                continue;
            }
            
            let def: MonsterDefinition = serde_json::from_value(value.clone())
                .map_err(|e| {
                    game_log!("[Loader] Failed to parse monster '{}': {}", key, e);
                    LoaderError::JsonParse {
                        path: format!("{} (monster: {})", path_str, key),
                        source: e,
                    }
                })?;
            
            // Build indexes
            let id = def.id.clone();
            by_name.insert(def.name.clone(), id.clone());
            if let Some(ref java_id) = def.java_id {
                by_java_id.insert(java_id.clone(), id.clone());
            }
            // Also index the JSON key name itself
            by_name.insert(key.clone(), id.clone());
            by_id.insert(id, def);
        }
        
        if by_id.is_empty() {
            return Err(LoaderError::EmptyMonsterLibrary(path_str));
        }
        
        game_log!("[Loader] Loaded {} monster definitions from '{}'", by_id.len(), path_str);
        
        Ok(Self { by_id, by_name, by_java_id })
    }
    
    /// Get a monster definition by id, name, or java_id.
    pub fn get(&self, query: &str) -> Result<&MonsterDefinition, LoaderError> {
        // Try direct id lookup first
        if let Some(def) = self.by_id.get(query) {
            return Ok(def);
        }
        // Try name index
        if let Some(id) = self.by_name.get(query) {
            if let Some(def) = self.by_id.get(id) {
                return Ok(def);
            }
        }
        // Try java_id index
        if let Some(id) = self.by_java_id.get(query) {
            if let Some(def) = self.by_id.get(id) {
                return Ok(def);
            }
        }
        Err(LoaderError::MonsterNotFound(query.to_string()))
    }
    
    /// Get a monster definition, returning None if not found.
    pub fn get_opt(&self, query: &str) -> Option<&MonsterDefinition> {
        self.get(query).ok()
    }
    
    /// Check if a monster exists in the library.
    pub fn contains(&self, query: &str) -> bool {
        self.get(query).is_ok()
    }
    
    /// Get the total number of monsters in the library.
    pub fn len(&self) -> usize {
        self.by_id.len()
    }
    
    /// Check if the library is empty.
    pub fn is_empty(&self) -> bool {
        self.by_id.is_empty()
    }
    
    /// Iterate over all monster definitions.
    pub fn iter(&self) -> impl Iterator<Item = &MonsterDefinition> {
        self.by_id.values()
    }
    
    /// Get all monster names.
    pub fn monster_names(&self) -> impl Iterator<Item = &String> {
        self.by_id.keys()
    }
    
    /// Filter monsters by act.
    pub fn monsters_in_act(&self, act: i32) -> Vec<&MonsterDefinition> {
        self.by_id
            .values()
            .filter(|m| m.act == act)
            .collect()
    }
    
    /// Filter monsters by type (normal, elite, boss, minion).
    pub fn monsters_of_type(&self, monster_type: &str) -> Vec<&MonsterDefinition> {
        self.by_id
            .values()
            .filter(|m| m.monster_type == monster_type)
            .collect()
    }
}

/// Load the default monster library from `data/monsters_verified.json`.
pub fn load_default_monsters() -> Result<MonsterLibrary, LoaderError> {
    MonsterLibrary::load("data/monsters_verified.json")
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_card_not_found_error() {
        let library = CardLibrary {
            cards: HashMap::new(),
        };
        
        let result = library.get("NonExistent");
        assert!(matches!(result, Err(LoaderError::CardNotFound(_))));
    }
    
    #[test]
    fn test_monster_not_found_error() {
        let library = MonsterLibrary {
            by_id: HashMap::new(),
            by_name: HashMap::new(),
            by_java_id: HashMap::new(),
        };
        
        let result = library.get("NonExistent");
        assert!(matches!(result, Err(LoaderError::MonsterNotFound(_))));
    }
}
