use crate::runtime::combat::{
    AwakenedOneRuntimeState, BookOfStabbingRuntimeState, BronzeAutomatonRuntimeState,
    BronzeOrbRuntimeState, ByrdRuntimeState, ChampRuntimeState, ChosenRuntimeState,
    CollectorRuntimeState, CorruptHeartRuntimeState, CultistRuntimeState, DarklingRuntimeState,
    DecaRuntimeState, DonuRuntimeState, ExploderRuntimeState, GiantHeadRuntimeState,
    GremlinLeaderRuntimeState, GremlinNobRuntimeState, GremlinWizardRuntimeState,
    GuardianRuntimeState, HexaghostRuntimeState, JawWormRuntimeState, LagavulinRuntimeState,
    LargeSlimeRuntimeState, LouseRuntimeState, MawRuntimeState, MonsterMoveState,
    NemesisRuntimeState, ReptomancerRuntimeState, SentryRuntimeState, ShelledParasiteRuntimeState,
    SlaverRedRuntimeState, SlimeBossRuntimeState, SnakeDaggerRuntimeState, SneckoRuntimeState,
    SphericGuardianRuntimeState, SpikerRuntimeState, SpireShieldRuntimeState,
    SpireSpearRuntimeState, ThiefRuntimeState, TimeEaterRuntimeState, TransientRuntimeState,
    WrithingMassRuntimeState,
};

/// Exact monster identity without duplicating its derived turn plan.
///
/// `MonsterEntity::turn_plan()` is wholly determined by `move_state`,
/// `is_dying`, and `half_dead`, all of which are already part of this key.
/// Keeping a second owned plan cloned its steps and visible specification for
/// every transposition. Durable identity now encodes `move_state` directly,
/// so the historical derived turn-plan compatibility view is unnecessary.
#[derive(Clone, Debug, PartialEq, Eq, Hash, serde::Serialize)]
pub(crate) struct CombatMonsterKey {
    pub(crate) entity_id: usize,
    pub(crate) monster_type: usize,
    pub(crate) current_hp: i32,
    pub(crate) max_hp: i32,
    pub(crate) block: i32,
    pub(crate) slot: u8,
    pub(crate) logical_position: i32,
    pub(crate) is_dying: bool,
    pub(crate) is_escaped: bool,
    pub(crate) half_dead: bool,
    pub(crate) move_state: MonsterMoveState,
    pub(crate) runtime: CombatMonsterRuntimeKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, serde::Serialize)]
pub(crate) enum CombatMonsterRuntimeKey {
    None,
    Hexaghost(HexaghostRuntimeState),
    Louse(LouseRuntimeState),
    JawWorm(JawWormRuntimeState),
    Thief(ThiefRuntimeState),
    Byrd(ByrdRuntimeState),
    Chosen(ChosenRuntimeState),
    Snecko(SneckoRuntimeState),
    ShelledParasite(ShelledParasiteRuntimeState),
    BronzeAutomaton(BronzeAutomatonRuntimeState),
    BronzeOrb(BronzeOrbRuntimeState),
    BookOfStabbing(BookOfStabbingRuntimeState),
    Collector(CollectorRuntimeState),
    Champ(ChampRuntimeState),
    AwakenedOne(AwakenedOneRuntimeState),
    CorruptHeart(CorruptHeartRuntimeState),
    WrithingMass(WrithingMassRuntimeState),
    Spiker(SpikerRuntimeState),
    SpireShield(SpireShieldRuntimeState),
    SpireSpear(SpireSpearRuntimeState),
    SlaverRed(SlaverRedRuntimeState),
    GremlinLeader(GremlinLeaderRuntimeState),
    GremlinNob(GremlinNobRuntimeState),
    GremlinWizard(GremlinWizardRuntimeState),
    Cultist(CultistRuntimeState),
    Sentry(SentryRuntimeState),
    SlimeBoss(SlimeBossRuntimeState),
    LargeSlime(LargeSlimeRuntimeState),
    SphericGuardian(SphericGuardianRuntimeState),
    Reptomancer(ReptomancerRuntimeState),
    Darkling(DarklingRuntimeState),
    Nemesis(NemesisRuntimeState),
    GiantHead(GiantHeadRuntimeState),
    TimeEater(TimeEaterRuntimeState),
    Donu(DonuRuntimeState),
    Deca(DecaRuntimeState),
    Transient(TransientRuntimeState),
    Exploder(ExploderRuntimeState),
    Maw(MawRuntimeState),
    SnakeDagger(SnakeDaggerRuntimeState),
    Lagavulin(LagavulinRuntimeState),
    Guardian(GuardianRuntimeState),
    /// Preserves exactness for simulator extensions whose numeric monster id
    /// is not yet represented by `EnemyId`, without making every known
    /// monster carry all inactive runtime records inline.
    Unknown(Box<CombatMonsterRuntimeFallbackKey>),
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, serde::Serialize)]
pub(crate) struct CombatMonsterRuntimeFallbackKey {
    pub(crate) hexaghost: HexaghostRuntimeState,
    pub(crate) louse: LouseRuntimeState,
    pub(crate) jaw_worm: JawWormRuntimeState,
    pub(crate) thief: ThiefRuntimeState,
    pub(crate) byrd: ByrdRuntimeState,
    pub(crate) chosen: ChosenRuntimeState,
    pub(crate) snecko: SneckoRuntimeState,
    pub(crate) shelled_parasite: ShelledParasiteRuntimeState,
    pub(crate) bronze_automaton: BronzeAutomatonRuntimeState,
    pub(crate) bronze_orb: BronzeOrbRuntimeState,
    pub(crate) book_of_stabbing: BookOfStabbingRuntimeState,
    pub(crate) collector: CollectorRuntimeState,
    pub(crate) champ: ChampRuntimeState,
    pub(crate) awakened_one: AwakenedOneRuntimeState,
    pub(crate) corrupt_heart: CorruptHeartRuntimeState,
    pub(crate) writhing_mass: WrithingMassRuntimeState,
    pub(crate) spiker: SpikerRuntimeState,
    pub(crate) spire_shield: SpireShieldRuntimeState,
    pub(crate) spire_spear: SpireSpearRuntimeState,
    pub(crate) slaver_red: SlaverRedRuntimeState,
    pub(crate) gremlin_leader: GremlinLeaderRuntimeState,
    pub(crate) gremlin_nob: GremlinNobRuntimeState,
    pub(crate) gremlin_wizard: GremlinWizardRuntimeState,
    pub(crate) cultist: CultistRuntimeState,
    pub(crate) sentry: SentryRuntimeState,
    pub(crate) slime_boss: SlimeBossRuntimeState,
    pub(crate) large_slime: LargeSlimeRuntimeState,
    pub(crate) spheric_guardian: SphericGuardianRuntimeState,
    pub(crate) reptomancer: ReptomancerRuntimeState,
    pub(crate) darkling: DarklingRuntimeState,
    pub(crate) nemesis: NemesisRuntimeState,
    pub(crate) giant_head: GiantHeadRuntimeState,
    pub(crate) time_eater: TimeEaterRuntimeState,
    pub(crate) donu: DonuRuntimeState,
    pub(crate) deca: DecaRuntimeState,
    pub(crate) transient: TransientRuntimeState,
    pub(crate) exploder: ExploderRuntimeState,
    pub(crate) maw: MawRuntimeState,
    pub(crate) snake_dagger: SnakeDaggerRuntimeState,
    pub(crate) lagavulin: LagavulinRuntimeState,
    pub(crate) guardian: GuardianRuntimeState,
}
