use crate::runtime::combat::{
    AwakenedOneRuntimeState, BookOfStabbingRuntimeState, BronzeAutomatonRuntimeState,
    BronzeOrbRuntimeState, ByrdRuntimeState, ChampRuntimeState, ChosenRuntimeState,
    CollectorRuntimeState, CorruptHeartRuntimeState, CultistRuntimeState, DarklingRuntimeState,
    DecaRuntimeState, DonuRuntimeState, ExploderRuntimeState, GiantHeadRuntimeState,
    GremlinLeaderRuntimeState, GremlinNobRuntimeState, GremlinWizardRuntimeState,
    GuardianRuntimeState, HexaghostRuntimeState, JawWormRuntimeState, LagavulinRuntimeState,
    LargeSlimeRuntimeState, LouseRuntimeState, MawRuntimeState, MonsterMoveState,
    NemesisRuntimeState, ReptomancerRuntimeState, SentryRuntimeState, ShelledParasiteRuntimeState,
    SlaverRedRuntimeState, SlimeBossRuntimeState, SnakeDaggerRuntimeState, SneckoRuntimeState,
    SphericGuardianRuntimeState, SpikerRuntimeState, SpireShieldRuntimeState,
    SpireSpearRuntimeState, ThiefRuntimeState, TimeEaterRuntimeState, TransientRuntimeState,
    WrithingMassRuntimeState,
};
use crate::runtime::monster_move::MonsterTurnPlan;

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub(crate) struct CombatMonsterKey {
    pub(crate) entity_id: usize,
    pub(crate) monster_type: usize,
    pub(crate) current_hp: i32,
    pub(crate) max_hp: i32,
    pub(crate) block: i32,
    pub(crate) slot: u8,
    pub(crate) logical_position: i32,
    pub(crate) is_dying: bool,
    pub(crate) is_escaped: bool,
    pub(crate) half_dead: bool,
    pub(crate) move_state: MonsterMoveState,
    pub(crate) turn_plan: MonsterTurnPlan,
    pub(crate) runtime: CombatMonsterRuntimeKey,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash)]
pub(crate) struct CombatMonsterRuntimeKey {
    pub(crate) hexaghost: HexaghostRuntimeState,
    pub(crate) louse: LouseRuntimeState,
    pub(crate) jaw_worm: JawWormRuntimeState,
    pub(crate) thief: ThiefRuntimeState,
    pub(crate) byrd: ByrdRuntimeState,
    pub(crate) chosen: ChosenRuntimeState,
    pub(crate) snecko: SneckoRuntimeState,
    pub(crate) shelled_parasite: ShelledParasiteRuntimeState,
    pub(crate) bronze_automaton: BronzeAutomatonRuntimeState,
    pub(crate) bronze_orb: BronzeOrbRuntimeState,
    pub(crate) book_of_stabbing: BookOfStabbingRuntimeState,
    pub(crate) collector: CollectorRuntimeState,
    pub(crate) champ: ChampRuntimeState,
    pub(crate) awakened_one: AwakenedOneRuntimeState,
    pub(crate) corrupt_heart: CorruptHeartRuntimeState,
    pub(crate) writhing_mass: WrithingMassRuntimeState,
    pub(crate) spiker: SpikerRuntimeState,
    pub(crate) spire_shield: SpireShieldRuntimeState,
    pub(crate) spire_spear: SpireSpearRuntimeState,
    pub(crate) slaver_red: SlaverRedRuntimeState,
    pub(crate) gremlin_leader: GremlinLeaderRuntimeState,
    pub(crate) gremlin_nob: GremlinNobRuntimeState,
    pub(crate) gremlin_wizard: GremlinWizardRuntimeState,
    pub(crate) cultist: CultistRuntimeState,
    pub(crate) sentry: SentryRuntimeState,
    pub(crate) slime_boss: SlimeBossRuntimeState,
    pub(crate) large_slime: LargeSlimeRuntimeState,
    pub(crate) spheric_guardian: SphericGuardianRuntimeState,
    pub(crate) reptomancer: ReptomancerRuntimeState,
    pub(crate) darkling: DarklingRuntimeState,
    pub(crate) nemesis: NemesisRuntimeState,
    pub(crate) giant_head: GiantHeadRuntimeState,
    pub(crate) time_eater: TimeEaterRuntimeState,
    pub(crate) donu: DonuRuntimeState,
    pub(crate) deca: DecaRuntimeState,
    pub(crate) transient: TransientRuntimeState,
    pub(crate) exploder: ExploderRuntimeState,
    pub(crate) maw: MawRuntimeState,
    pub(crate) snake_dagger: SnakeDaggerRuntimeState,
    pub(crate) lagavulin: LagavulinRuntimeState,
    pub(crate) guardian: GuardianRuntimeState,
}
