from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


DEFAULT_REPO_ROOT = Path(r"D:\rust\sts_simulator")
DEFAULT_RAW_PATH = DEFAULT_REPO_ROOT / "live_comm_raw.jsonl"
DEFAULT_DEBUG_PATH = DEFAULT_REPO_ROOT / "live_comm_debug.txt"
DEFAULT_OUT_DIR = DEFAULT_REPO_ROOT / "tests" / "live_regressions"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "_", value)
    return value.strip("_") or "bug"


def run_checked(command: list[str], cwd: Path) -> None:
    print("+", " ".join(str(part) for part in command))
    subprocess.run(command, cwd=cwd, check=True)


def run_capture(command: list[str], cwd: Path) -> subprocess.CompletedProcess[str]:
    print("+", " ".join(str(part) for part in command))
    return subprocess.run(
        command,
        cwd=cwd,
        check=False,
        capture_output=True,
        text=True,
    )


def field_fallbacks(field: str) -> list[str]:
    fallbacks = [field]
    if ".power[" in field and not field.endswith(".amount"):
        fallbacks.append(f"{field}.amount")
    return fallbacks


def write_notes_template(
    *,
    notes_path: Path,
    field: str,
    from_response_id: int,
    to_response_id: int,
    extracted_path: Path,
    minimized_path: Path,
    raw_path: Path,
    debug_path: Path,
) -> None:
    notes_path.write_text(
        f"""# Bugfix Note: {field}

## Scope
- Target field: `{field}`
- Response window: `{from_response_id}..{to_response_id}`
- Raw log: `{raw_path}`
- Debug log: `{debug_path}`
- Extracted fixture: `{extracted_path}`
- Minimized fixture: `{minimized_path}`

## Required Workflow
- [ ] Reproduce with minimized fixture first
- [ ] Read Java source before editing Rust
- [ ] Write or update a targeted regression test before/with the fix
- [ ] Re-run targeted test, then `cargo test -q`
- [ ] Re-run `live_comm` after the fix

## Java Source To Inspect
- [ ] Primary class:
- [ ] Related powers / relics / actions:
- [ ] Hidden internal state involved:

## Rust Touchpoints
- [ ] state sync / snapshot build:
- [ ] engine action handler:
- [ ] content entity implementation:
- [ ] comparator / replay support:

## Root Cause
- Pending

## Regression Target
- Pending

## Notes
- This note was generated by `tools/analysis/bugfix_workflow.py`.
- Do not start broad edits from the raw log alone; use the minimized fixture first.
""",
        encoding="utf-8",
    )


def cmd_from_live(args: argparse.Namespace) -> int:
    repo_root = args.repo_root.resolve()
    out_dir = args.out_dir.resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    live_regression = repo_root / "tools" / "analysis" / "live_regression.py"
    slug = args.name or f"{slugify(args.field)}_r{args.from_response_id}_{args.to_response_id}"
    extracted_path = out_dir / f"{slug}.json"
    minimized_path = out_dir / f"{slug}.min.json"
    notes_path = out_dir / f"{slug}.notes.md"

    common = [
        sys.executable,
        str(live_regression),
    ]

    chosen_field: str | None = None
    last_error: subprocess.CompletedProcess[str] | None = None
    for candidate_field in field_fallbacks(args.field):
        extract_cmd = common + [
            "extract",
            "--raw-path",
            str(args.raw_path),
            "--debug-path",
            str(args.debug_path),
            "--from-response-id",
            str(args.from_response_id),
            "--to-response-id",
            str(args.to_response_id),
            "--field",
            candidate_field,
            "--out",
            str(extracted_path),
        ]
        result = run_capture(extract_cmd, repo_root)
        if result.stdout:
            print(result.stdout, end="")
        if result.returncode == 0:
            if result.stderr:
                print(result.stderr, end="", file=sys.stderr)
            chosen_field = candidate_field
            break
        last_error = result

    if chosen_field is None:
        assert last_error is not None
        if last_error.stdout:
            print(last_error.stdout, end="")
        if last_error.stderr:
            print(last_error.stderr, end="", file=sys.stderr)
        raise SystemExit(last_error.returncode)

    minimize_cmd = common + [
        "minimize",
        "--fixture",
        str(extracted_path),
        "--raw-path",
        str(args.raw_path),
        "--debug-path",
        str(args.debug_path),
        "--repo-root",
        str(repo_root),
        "--field",
        chosen_field,
        "--mode",
        args.mode,
        "--out",
        str(minimized_path),
    ]
    run_checked(minimize_cmd, repo_root)

    write_notes_template(
        notes_path=notes_path,
        field=chosen_field,
        from_response_id=args.from_response_id,
        to_response_id=args.to_response_id,
        extracted_path=extracted_path,
        minimized_path=minimized_path,
        raw_path=args.raw_path,
        debug_path=args.debug_path,
    )

    print()
    print("Bugfix workflow artifacts written:")
    print(f"- extracted: {extracted_path}")
    print(f"- minimized: {minimized_path}")
    print(f"- notes:     {notes_path}")
    print()
    print("Next steps:")
    print(f"1. Reproduce with: set FIXTURE={minimized_path}")
    print("2. Fill the Java/Rust touchpoints in the notes file")
    print("3. Add a targeted regression before broad changes")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Opinionated bugfix workflow wrapper for live_comm parity issues."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    from_live = sub.add_parser(
        "from-live",
        help="extract + minimize a field-specific live_comm bug and generate a notes template",
    )
    from_live.add_argument("--field", required=True, help="field to preserve, e.g. player.energy")
    from_live.add_argument("--from-response-id", type=int, required=True)
    from_live.add_argument("--to-response-id", type=int, required=True)
    from_live.add_argument(
        "--name",
        help="optional artifact stem; defaults to '<field>_r<from>_<to>'",
    )
    from_live.add_argument("--raw-path", type=Path, default=DEFAULT_RAW_PATH)
    from_live.add_argument("--debug-path", type=Path, default=DEFAULT_DEBUG_PATH)
    from_live.add_argument("--repo-root", type=Path, default=DEFAULT_REPO_ROOT)
    from_live.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    from_live.add_argument(
        "--mode",
        choices=("same-outcome", "pass-only", "fail-only"),
        default="same-outcome",
        help="fixture minimization mode",
    )
    from_live.set_defaults(func=cmd_from_live)
    return parser


def main() -> int:
    parser = build_parser()
    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
